-- MultiPréstamos — esquema inicial.
-- Ejecutar en Supabase: panel → SQL Editor → pegar → Run.
-- El script es repetible: vuelve a crear las políticas RLS con la misma configuración.

begin;

create table if not exists clientes (
  id uuid primary key default gen_random_uuid(),
  nombre text not null,
  identidad text,
  telefono text,
  direccion text,
  lugar_trabajo text,
  referencias text,
  foto_fachada_path text,
  estado text not null default 'activo'
    check (estado in ('activo', 'moroso', 'cancelado')),
  notas text,
  creado_en timestamptz not null default now()
);

-- Un solo prestamista/negocio durante el MVP. No se crea una fila por defecto:
-- su ausencia activa la configuración inicial después del primer login.
create table if not exists configuracion_prestamista (
  id smallint primary key default 1 check (id = 1),
  nombre_negocio text not null check (btrim(nombre_negocio) <> ''),
  nombre_propietario text not null check (btrim(nombre_propietario) <> ''),
  rtn text,
  direccion text,
  telefono text,
  prefijo_recibo text not null default 'REC',
  digitos_recibo smallint not null default 6,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table if not exists prestamos (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity unique,
  cliente_id uuid not null,
  monto numeric(14,2) not null check (monto > 0),
  tasa_interes numeric(6,2) not null default 0
    constraint prestamos_tasa_no_negativa check (tasa_interes >= 0),
  plazo integer not null check (plazo > 0),
  frecuencia text not null
    constraint prestamos_frecuencia_valida
    check (frecuencia in ('diario', 'semanal', 'quincenal', 'mensual')),
  fecha_inicio date not null default ((clock_timestamp() at time zone 'America/Tegucigalpa')::date),
  fecha_primer_pago date,
  dia_pago_semana smallint,
  tasa_mora numeric(5,2) not null default 1.50
    constraint prestamos_tasa_mora_no_negativa check (tasa_mora >= 0),
  saldo numeric(14,2) not null
    constraint prestamos_saldo_no_negativo check (saldo >= 0),
  estado text not null default 'activo'
    check (estado in ('activo', 'al_dia', 'en_mora', 'pagado', 'cancelado')),
  solicitud_id uuid,
  creado_en timestamptz not null default now()
);

create table if not exists cuotas (
  id uuid primary key default gen_random_uuid(),
  prestamo_id uuid not null references prestamos(id) on delete cascade,
  numero integer not null
    constraint cuotas_numero_positivo check (numero > 0),
  fecha_vencimiento date not null,
  monto numeric(14,2) not null
    constraint cuotas_monto_positivo check (monto > 0),
  monto_pagado numeric(14,2) not null default 0,
  estado text not null default 'pendiente'
    check (estado in ('pendiente', 'pagada', 'vencida')),
  unique (prestamo_id, numero),
  constraint cuotas_id_prestamo_unique unique (id, prestamo_id)
);

create table if not exists pagos (
  id uuid primary key default gen_random_uuid(),
  prestamo_id uuid not null references prestamos(id),
  cuota_id uuid,
  solicitud_id uuid not null default gen_random_uuid(),
  numero_recibo bigint generated by default as identity unique,
  fecha timestamptz not null default now(),
  monto numeric(14,2) not null check (monto > 0),
  recibo text,
  saldo_anterior numeric(14,2),
  saldo_posterior numeric(14,2),
  notas text,
  datos_recibo jsonb,
  creado_en timestamptz not null default now(),
  constraint pagos_id_prestamo_unique unique (id, prestamo_id),
  constraint pagos_cuota_prestamo_fk
    foreign key (cuota_id, prestamo_id) references cuotas(id, prestamo_id)
);

-- Las FK compuestas necesitan estas claves aun cuando las tablas provengan
-- del esquema anterior. Deben existir antes de crear `pago_aplicaciones`.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'cuotas_id_prestamo_unique' and conrelid = 'public.cuotas'::regclass
  ) then
    alter table cuotas add constraint cuotas_id_prestamo_unique unique (id, prestamo_id);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'pagos_id_prestamo_unique' and conrelid = 'public.pagos'::regclass
  ) then
    alter table pagos add constraint pagos_id_prestamo_unique unique (id, prestamo_id);
  end if;
end $$;

-- Un pago puede cubrir varias cuotas. Esta tabla guarda ese reparto mientras
-- `pagos` conserva una sola fila por operación y por recibo.
create table if not exists pago_aplicaciones (
  id uuid primary key default gen_random_uuid(),
  pago_id uuid not null,
  prestamo_id uuid not null,
  cuota_id uuid not null,
  monto numeric(14,2) not null check (monto > 0),
  creado_en timestamptz not null default now(),
  constraint pago_aplicaciones_pago_fk
    foreign key (pago_id, prestamo_id) references pagos(id, prestamo_id) on delete cascade,
  constraint pago_aplicaciones_cuota_fk
    foreign key (cuota_id, prestamo_id) references cuotas(id, prestamo_id),
  constraint pago_aplicaciones_pago_cuota_unique unique (pago_id, cuota_id)
);

-- Bitácora de visitas de cobranza en campo: una fila por gestión (con o sin
-- cobro). `pago_id` enlaza la gestión con el pago cuando la visita cobró.
create table if not exists gestiones (
  id uuid primary key default gen_random_uuid(),
  cliente_id uuid not null references clientes(id),
  fecha timestamptz not null default now(),
  resultado text not null,
  monto_prometido numeric(14,2),
  fecha_promesa date,
  pago_id uuid references pagos(id),
  notas text,
  creado_en timestamptz not null default now()
);

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'gestiones_resultado_valido' and conrelid = 'public.gestiones'::regclass
  ) then
    alter table gestiones add constraint gestiones_resultado_valido
      check (resultado in ('pago', 'no_estaba', 'promesa_pago', 'se_nego', 'otro'));
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'gestiones_promesa_completa' and conrelid = 'public.gestiones'::regclass
  ) then
    alter table gestiones add constraint gestiones_promesa_completa
      check (resultado <> 'promesa_pago' or (monto_prometido > 0 and fecha_promesa is not null));
  end if;
end $$;

-- Migraciones idempotentes para proyectos donde las tablas ya existían antes
-- de agregar estas validaciones.
alter table clientes add column if not exists lugar_trabajo text;
alter table clientes add column if not exists referencias text;
alter table clientes add column if not exists estado text not null default 'activo';
alter table clientes add column if not exists colonia text;
alter table clientes add column if not exists orden_ruta integer;
alter table clientes add column if not exists foto_fachada_path text;

alter table configuracion_prestamista add column if not exists nombre_negocio text;
alter table configuracion_prestamista add column if not exists nombre_propietario text;
alter table configuracion_prestamista add column if not exists rtn text;
alter table configuracion_prestamista add column if not exists direccion text;
alter table configuracion_prestamista add column if not exists telefono text;
alter table configuracion_prestamista add column if not exists prefijo_recibo text not null default 'REC';
alter table configuracion_prestamista add column if not exists digitos_recibo smallint not null default 6;
alter table configuracion_prestamista add column if not exists creado_en timestamptz not null default now();
alter table configuracion_prestamista add column if not exists actualizado_en timestamptz not null default now();

alter table prestamos add column if not exists solicitud_id uuid;
alter table prestamos add column if not exists numero bigint generated by default as identity;
alter table prestamos add column if not exists fecha_primer_pago date;
alter table prestamos add column if not exists dia_pago_semana smallint;
-- En una instalación existente la mora se deja en 0 para no cambiar contratos
-- vigentes. Después del backfill, el valor por defecto de nuevos préstamos es 1.5%.
alter table prestamos add column if not exists tasa_mora numeric(5,2);
update prestamos set tasa_mora = 0 where tasa_mora is null;
alter table prestamos alter column tasa_mora set default 1.50;
alter table prestamos alter column tasa_mora set not null;
alter table prestamos alter column fecha_inicio
  set default ((clock_timestamp() at time zone 'America/Tegucigalpa')::date);
alter table cuotas add column if not exists monto_pagado numeric(14,2) not null default 0;
alter table pagos add column if not exists solicitud_id uuid;
alter table pagos add column if not exists numero_recibo bigint generated by default as identity;
alter table pagos add column if not exists saldo_anterior numeric(14,2);
alter table pagos add column if not exists saldo_posterior numeric(14,2);
alter table pagos add column if not exists notas text;
alter table pagos add column if not exists datos_recibo jsonb;
alter table pagos add column if not exists creado_en timestamptz not null default now();

update clientes set estado = 'activo' where estado is null;
alter table clientes alter column estado set default 'activo';
alter table clientes alter column estado set not null;

-- Para préstamos previos toma la cuota 1; si no existe, deriva la fecha con
-- el mismo calendario fijo que utiliza la aplicación.
update prestamos p
set fecha_primer_pago = coalesce(
  (
    select c.fecha_vencimiento
    from cuotas c
    where c.prestamo_id = p.id
      and c.numero = 1
    limit 1
  ),
  case p.frecuencia
    when 'diario' then p.fecha_inicio + 1
    when 'semanal' then p.fecha_inicio + 7
    when 'quincenal' then p.fecha_inicio + 15
    else (p.fecha_inicio + make_interval(months => 1))::date
  end
)
where p.fecha_primer_pago is null;

alter table prestamos alter column numero set not null;
alter table prestamos alter column fecha_primer_pago set not null;

-- Cada pago histórico se conserva como una operación y, cuando apuntaba a
-- una cuota, se migra como una aplicación uno-a-uno sin adivinar agrupaciones.
update pagos set solicitud_id = id where solicitud_id is null;
alter table pagos alter column solicitud_id set not null;
alter table pagos alter column solicitud_id set default gen_random_uuid();

insert into pago_aplicaciones (pago_id, prestamo_id, cuota_id, monto, creado_en)
select id, prestamo_id, cuota_id, monto, fecha
from pagos
where cuota_id is not null
on conflict (pago_id, cuota_id) do nothing;

do $$
begin
  if exists (
    select 1
    from pago_aplicaciones a
    join cuotas c on c.id = a.cuota_id
    group by c.id, c.monto
    having sum(a.monto) > c.monto
  ) then
    raise exception 'Hay pagos históricos que exceden el monto de su cuota';
  end if;
end $$;

update cuotas c
set monto_pagado = datos.total
from (
  select cuota_id, sum(monto) as total
  from pago_aplicaciones
  group by cuota_id
) datos
where c.id = datos.cuota_id;

update cuotas
set monto_pagado = monto
where estado = 'pagada' and monto_pagado = 0;

-- No corregimos diferencias históricas silenciosamente: un saldo que no
-- coincide con sus cuotas debe revisarse antes de aceptar nuevos cobros.
do $$
declare
  v_prestamos text;
begin
  select string_agg(p.id::text, ', ' order by p.id::text)
  into v_prestamos
  from public.prestamos p
  where p.estado <> 'cancelado'
    and p.saldo is distinct from (
    select coalesce(sum(c.monto - c.monto_pagado), 0)
    from public.cuotas c
    where c.prestamo_id = p.id
  );

  if v_prestamos is not null then
    raise exception 'El saldo no coincide con las cuotas en préstamo(s): %', v_prestamos;
  end if;
end $$;

update pagos
set recibo = 'REC-' || lpad(numero_recibo::text, greatest(6, length(numero_recibo::text)), '0')
where recibo is null;

-- `create table if not exists` no actualiza el CHECK de instalaciones previas.
-- Se reemplaza con un nombre estable para aceptar el nuevo plan diario.
alter table public.prestamos drop constraint if exists prestamos_frecuencia_check;
alter table public.prestamos drop constraint if exists prestamos_frecuencia_valida;
alter table public.prestamos add constraint prestamos_frecuencia_valida
  check (frecuencia in ('diario', 'semanal', 'quincenal', 'mensual'));

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'clientes_estado_valido' and conrelid = 'public.clientes'::regclass
  ) then
    alter table clientes add constraint clientes_estado_valido
      check (estado in ('activo', 'moroso', 'cancelado'));
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'configuracion_prestamista_singleton'
      and conrelid = 'public.configuracion_prestamista'::regclass
  ) then
    alter table configuracion_prestamista add constraint configuracion_prestamista_singleton check (id = 1);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'configuracion_nombre_negocio_requerido'
      and conrelid = 'public.configuracion_prestamista'::regclass
  ) then
    alter table configuracion_prestamista add constraint configuracion_nombre_negocio_requerido
      check (nombre_negocio is not null and btrim(nombre_negocio) <> '');
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'configuracion_propietario_requerido'
      and conrelid = 'public.configuracion_prestamista'::regclass
  ) then
    alter table configuracion_prestamista add constraint configuracion_propietario_requerido
      check (nombre_propietario is not null and btrim(nombre_propietario) <> '');
  end if;
  if not exists (select 1 from pg_constraint where conname = 'prestamos_tasa_no_negativa' and conrelid = 'public.prestamos'::regclass) then
    alter table prestamos add constraint prestamos_tasa_no_negativa check (tasa_interes >= 0);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'prestamos_tasa_mora_no_negativa' and conrelid = 'public.prestamos'::regclass
  ) then
    alter table prestamos add constraint prestamos_tasa_mora_no_negativa check (tasa_mora >= 0);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'prestamos_dia_pago_semana_valido' and conrelid = 'public.prestamos'::regclass
  ) then
    alter table prestamos add constraint prestamos_dia_pago_semana_valido
      check (
        dia_pago_semana is null
        or (frecuencia = 'semanal' and dia_pago_semana between 1 and 6)
      );
  end if;
  if not exists (select 1 from pg_constraint where conname = 'prestamos_saldo_no_negativo' and conrelid = 'public.prestamos'::regclass) then
    alter table prestamos add constraint prestamos_saldo_no_negativo check (saldo >= 0);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'cuotas_numero_positivo' and conrelid = 'public.cuotas'::regclass) then
    alter table cuotas add constraint cuotas_numero_positivo check (numero > 0);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'cuotas_monto_positivo' and conrelid = 'public.cuotas'::regclass) then
    alter table cuotas add constraint cuotas_monto_positivo check (monto > 0);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'cuotas_monto_pagado_valido' and conrelid = 'public.cuotas'::regclass
  ) then
    alter table cuotas add constraint cuotas_monto_pagado_valido
      check (monto_pagado >= 0 and monto_pagado <= monto);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'cuotas_id_prestamo_unique' and conrelid = 'public.cuotas'::regclass) then
    alter table cuotas add constraint cuotas_id_prestamo_unique unique (id, prestamo_id);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'pagos_cuota_prestamo_fk' and conrelid = 'public.pagos'::regclass) then
    alter table pagos add constraint pagos_cuota_prestamo_fk
      foreign key (cuota_id, prestamo_id) references cuotas(id, prestamo_id);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'pagos_id_prestamo_unique' and conrelid = 'public.pagos'::regclass
  ) then
    alter table pagos add constraint pagos_id_prestamo_unique unique (id, prestamo_id);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'pagos_solicitud_id_unique' and conrelid = 'public.pagos'::regclass
  ) then
    alter table pagos add constraint pagos_solicitud_id_unique unique (solicitud_id);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'configuracion_prefijo_recibo_valido'
      and conrelid = 'public.configuracion_prestamista'::regclass
  ) then
    alter table configuracion_prestamista add constraint configuracion_prefijo_recibo_valido
      check (char_length(btrim(prefijo_recibo)) between 1 and 10);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'configuracion_digitos_recibo_valido'
      and conrelid = 'public.configuracion_prestamista'::regclass
  ) then
    alter table configuracion_prestamista add constraint configuracion_digitos_recibo_valido
      check (digitos_recibo between 3 and 12);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'prestamos_solicitud_id_unique' and conrelid = 'public.prestamos'::regclass) then
    alter table prestamos add constraint prestamos_solicitud_id_unique unique (solicitud_id);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'prestamos_fecha_primer_pago_valida'
      and conrelid = 'public.prestamos'::regclass
  ) then
    alter table prestamos add constraint prestamos_fecha_primer_pago_valida
      check (fecha_primer_pago >= fecha_inicio);
  end if;
end $$;

create index if not exists idx_prestamos_cliente on prestamos (cliente_id);
create unique index if not exists idx_prestamos_numero_unique on prestamos (numero);
create index if not exists idx_prestamos_fecha_primer_pago on prestamos (fecha_primer_pago);
create index if not exists idx_cuotas_prestamo on cuotas (prestamo_id);
create index if not exists idx_pagos_prestamo on pagos (prestamo_id);
create index if not exists idx_pagos_fecha on pagos (fecha);
create unique index if not exists idx_pagos_numero_recibo_unique on pagos (numero_recibo);
create index if not exists idx_pago_aplicaciones_pago on pago_aplicaciones (pago_id);
create index if not exists idx_pago_aplicaciones_cuota on pago_aplicaciones (cuota_id);
create index if not exists idx_pago_aplicaciones_prestamo on pago_aplicaciones (prestamo_id);
create index if not exists idx_gestiones_cliente_fecha on gestiones (cliente_id, fecha desc);
create index if not exists idx_gestiones_fecha on gestiones (fecha);
-- La ruta de cobro lee todas las cuotas no pagadas de la cartera.
create index if not exists idx_cuotas_estado_vencimiento on cuotas (estado, fecha_vencimiento);

-- ============================================================
-- Usuarios, roles y empresas (admin / prestamista, ampliable)
-- ============================================================
-- Cada instalación tiene una o más empresas; cada usuario de Supabase Auth
-- tiene un `profiles` con su rol y su empresa. El rol solo controla permisos
-- administrativos: la cartera (clientes/prestamos) se reparte por
-- `prestamista_id` dentro de la misma empresa, y se reasigna sin perder el
-- historial de pagos/gestiones (que quedan con su propio `registrado_por`).

create table if not exists empresas (
  id uuid primary key default gen_random_uuid(),
  nombre text not null check (btrim(nombre) <> ''),
  activo boolean not null default true,
  creado_en timestamptz not null default now()
);

-- El check incluye roles futuros (gerente/cobrador/supervisor) para que la
-- base no rechace datos cuando la interfaz los habilite; hoy solo se usan
-- 'admin' y 'prestamista', y cualquier rol distinto de 'admin' recibe el
-- mismo trato restringido que 'prestamista' hasta que se defina lo contrario.
create table if not exists profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  empresa_id uuid not null references empresas(id),
  nombre text not null check (btrim(nombre) <> ''),
  apellido text,
  email text not null,
  telefono text,
  rol text not null default 'prestamista'
    check (rol in ('admin', 'prestamista', 'gerente', 'cobrador', 'supervisor')),
  activo boolean not null default true,
  creado_por uuid references profiles(id),
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);
alter table profiles add column if not exists apellido text;
alter table profiles add column if not exists telefono text;
alter table profiles add column if not exists activo boolean not null default true;
alter table profiles add column if not exists creado_por uuid references profiles(id);
alter table profiles add column if not exists actualizado_en timestamptz not null default now();
create index if not exists idx_profiles_empresa on profiles (empresa_id);

-- Instalación existente sin empresas/perfiles: crea la empresa por defecto
-- (con el nombre del negocio ya configurado, si existe) y da rol admin a
-- todos los usuarios de Supabase Auth que ya existían antes de esta migración.
do $$
declare
  v_empresa_id uuid;
  v_master_id uuid;
begin
  -- Este bloque es exclusivamente una migracion del MVP de una sola empresa.
  -- Una vez que existe cualquier perfil, un usuario de Auth sin ficha NO se
  -- adopta silenciosamente por la primera empresa: las empresas nuevas se dan
  -- de alta con `provisionar_empresa_master`, usando service_role.
  if not exists (select 1 from profiles) then
    select u.id
    into v_master_id
    from auth.users u
    order by u.created_at, u.id
    limit 1;

    if v_master_id is not null then
      if not exists (select 1 from empresas) then
        insert into empresas (nombre)
        values (coalesce(
          nullif(btrim((select nombre_negocio from configuracion_prestamista where id = 1)), ''),
          'Mi Empresa'
        ))
        returning id into v_empresa_id;
      else
        select id into v_empresa_id from empresas order by creado_en, id limit 1;
      end if;

      insert into profiles (id, empresa_id, nombre, email, rol, activo)
      select
        u.id,
        v_empresa_id,
        coalesce(nullif(btrim(split_part(u.email, '@', 1)), ''), 'Administrador'),
        lower(u.email),
        case when u.id = v_master_id then 'admin' else 'prestamista' end,
        true
      from auth.users u;

      update profiles
      set creado_por = v_master_id
      where empresa_id = v_empresa_id and id <> v_master_id and creado_por is null;
    end if;
  end if;
end $$;

-- Funciones auxiliares "security definer": leen `profiles` sin pasar por su
-- propia RLS (evita el error de recursión) y sirven de base a todas las
-- políticas de abajo.
create or replace function public.current_empresa_id()
returns uuid
language sql
security definer
stable
set search_path = ''
as $$
  select empresa_id from public.profiles where id = auth.uid();
$$;

create or replace function public.is_admin()
returns boolean
language sql
security definer
stable
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles p
    join public.empresas e on e.id = p.empresa_id
    where p.id = auth.uid() and p.rol = 'admin' and p.activo and e.activo
  );
$$;

create or replace function public.is_active_profile()
returns boolean
language sql
security definer
stable
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles p
    join public.empresas e on e.id = p.empresa_id
    where p.id = auth.uid() and p.activo and e.activo
  );
$$;

revoke all on function public.current_empresa_id() from public, anon;
grant execute on function public.current_empresa_id() to authenticated;
revoke all on function public.is_admin() from public, anon;
grant execute on function public.is_admin() to authenticated;
revoke all on function public.is_active_profile() from public, anon;
grant execute on function public.is_active_profile() to authenticated;

-- Migra instalaciones que llegaron a tener varios administradores por el
-- bootstrap anterior. El perfil admin mas antiguo queda como la unica cuenta
-- maestra; los demas conservan acceso como prestamistas. Si una empresa tenia
-- perfiles pero ningun admin, se promueve deterministicamente el mas antiguo.
with admins_ordenados as (
  select
    id,
    row_number() over (partition by empresa_id order by creado_en, id) as posicion
  from profiles
  where rol = 'admin'
)
update profiles p
set activo = true
from admins_ordenados a
where p.id = a.id and a.posicion = 1 and not p.activo;

with admins_ordenados as (
  select
    id,
    row_number() over (partition by empresa_id order by creado_en, id) as posicion
  from profiles
  where rol = 'admin'
)
update profiles p
set rol = 'prestamista'
from admins_ordenados a
where p.id = a.id and a.posicion > 1;

with candidatos as (
  select
    p.id,
    row_number() over (partition by p.empresa_id order by p.creado_en, p.id) as posicion
  from profiles p
  where not exists (
    select 1 from profiles master
    where master.empresa_id = p.empresa_id and master.rol = 'admin'
  )
)
update profiles p
set rol = 'admin', activo = true
from candidatos c
where p.id = c.id and c.posicion = 1;

do $$
declare
  v_empresas_sin_master text;
begin
  select string_agg(e.id::text, ', ' order by e.id::text)
  into v_empresas_sin_master
  from empresas e
  where not exists (select 1 from profiles p where p.empresa_id = e.id and p.rol = 'admin' and p.activo);

  if v_empresas_sin_master is not null then
    raise exception 'Hay empresa(s) sin una cuenta maestra y sin perfil que promover: %', v_empresas_sin_master;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'profiles_admin_siempre_activo'
      and conrelid = 'public.profiles'::regclass
  ) then
    alter table profiles add constraint profiles_admin_siempre_activo
      check (rol <> 'admin' or activo);
  end if;
end $$;

create unique index if not exists profiles_un_admin_por_empresa
  on profiles (empresa_id) where rol = 'admin';
create unique index if not exists profiles_id_empresa_unique
  on profiles (id, empresa_id);
create unique index if not exists profiles_email_normalizado_unique
  on profiles (lower(email));

-- La configuracion deja de ser un singleton global. `id = 1` se conserva
-- para que clientes antiguos sigan leyendo la misma forma de fila, mientras
-- `empresa_id` pasa a ser la clave primaria y frontera real de aislamiento.
alter table configuracion_prestamista add column if not exists empresa_id uuid;

do $$
declare
  v_empresa_id uuid;
begin
  if exists (select 1 from configuracion_prestamista where empresa_id is null) then
    select id into v_empresa_id from empresas order by creado_en, id limit 1;
    if v_empresa_id is null then
      raise exception 'No se puede migrar la configuracion sin una empresa existente';
    end if;
    update configuracion_prestamista set empresa_id = v_empresa_id where empresa_id is null;
  end if;
end $$;

alter table configuracion_prestamista
  alter column empresa_id set default public.current_empresa_id();
alter table configuracion_prestamista alter column empresa_id set not null;

do $$
declare
  v_pkey_name text;
begin
  select conname into v_pkey_name
  from pg_constraint
  where conrelid = 'public.configuracion_prestamista'::regclass and contype = 'p';

  if v_pkey_name is not null and not exists (
    select 1
    from pg_constraint c
    join pg_attribute a
      on a.attrelid = c.conrelid and a.attname = 'empresa_id'
    where c.conrelid = 'public.configuracion_prestamista'::regclass
      and c.contype = 'p'
      and cardinality(c.conkey) = 1
      and c.conkey[1] = a.attnum
  ) then
    execute format('alter table public.configuracion_prestamista drop constraint %I', v_pkey_name);
    v_pkey_name := null;
  end if;

  if v_pkey_name is null then
    alter table configuracion_prestamista
      add constraint configuracion_prestamista_pkey primary key (empresa_id);
  end if;

  if not exists (
    select 1 from pg_constraint
    where conname = 'configuracion_prestamista_empresa_fk'
      and conrelid = 'public.configuracion_prestamista'::regclass
  ) then
    alter table configuracion_prestamista
      add constraint configuracion_prestamista_empresa_fk
      foreign key (empresa_id) references empresas(id) on delete cascade;
  end if;
end $$;

-- Comprobacion diferida: permite crear empresa + master en una misma
-- transaccion, pero impide confirmar una empresa sin exactamente un admin
-- activo. La unicidad parcial de arriba cubre el limite superior.
create or replace function public.assert_empresa_tiene_master(p_empresa_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if exists (select 1 from public.empresas e where e.id = p_empresa_id)
    and not exists (
      select 1 from public.profiles p
      where p.empresa_id = p_empresa_id and p.rol = 'admin' and p.activo
    ) then
    raise exception using
      message = 'Cada empresa debe conservar exactamente una cuenta maestra activa.',
      errcode = '23514';
  end if;
end;
$$;

create or replace function public.validar_empresa_master_profiles()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'DELETE' then
    perform public.assert_empresa_tiene_master(old.empresa_id);
  elsif tg_op = 'INSERT' then
    perform public.assert_empresa_tiene_master(new.empresa_id);
  else
    perform public.assert_empresa_tiene_master(old.empresa_id);
    if new.empresa_id is distinct from old.empresa_id then
      perform public.assert_empresa_tiene_master(new.empresa_id);
    end if;
  end if;
  return null;
end;
$$;

create or replace function public.validar_empresa_master_empresas()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  perform public.assert_empresa_tiene_master(new.id);
  return null;
end;
$$;

drop trigger if exists trg_profiles_empresa_master on profiles;
create constraint trigger trg_profiles_empresa_master
  after insert or update or delete on profiles
  deferrable initially deferred
  for each row execute function public.validar_empresa_master_profiles();

drop trigger if exists trg_empresas_master on empresas;
create constraint trigger trg_empresas_master
  after insert or update on empresas
  deferrable initially deferred
  for each row execute function public.validar_empresa_master_empresas();

revoke all on function public.assert_empresa_tiene_master(uuid) from public, anon, authenticated;
revoke all on function public.validar_empresa_master_profiles() from public, anon, authenticated;
revoke all on function public.validar_empresa_master_empresas() from public, anon, authenticated;

-- Alta operativa de una empresa y su unica cuenta maestra. Esta funcion NO
-- crea auth.users: el operador crea/invita primero el usuario con Admin Auth y
-- luego, usando service_role desde una Edge Function o proceso privado, llama
-- este RPC con su UUID. Empresa y profile se confirman atomicamente.
create or replace function public.provisionar_empresa_master(
  p_user_id uuid,
  p_empresa_nombre text,
  p_nombre text,
  p_apellido text default null,
  p_telefono text default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_empresa_id uuid;
  v_email text;
begin
  if p_user_id is null then
    raise exception using message = 'El usuario de Auth es obligatorio.', errcode = '23502';
  end if;
  if nullif(btrim(p_empresa_nombre), '') is null then
    raise exception using message = 'El nombre de la empresa es obligatorio.', errcode = '23514';
  end if;
  if nullif(btrim(p_nombre), '') is null then
    raise exception using message = 'El nombre de la cuenta maestra es obligatorio.', errcode = '23514';
  end if;

  select lower(u.email)
  into v_email
  from auth.users u
  where u.id = p_user_id
  for update;

  if not found or nullif(btrim(v_email), '') is null then
    raise exception using message = 'El usuario de Auth no existe o no tiene correo.', errcode = '23503';
  end if;
  if exists (select 1 from public.profiles p where p.id = p_user_id) then
    raise exception using message = 'El usuario ya pertenece a una empresa.', errcode = '23505';
  end if;

  insert into public.empresas (nombre)
  values (btrim(p_empresa_nombre))
  returning id into v_empresa_id;

  insert into public.profiles (
    id, empresa_id, nombre, apellido, email, telefono, rol, activo, creado_por
  ) values (
    p_user_id,
    v_empresa_id,
    btrim(p_nombre),
    nullif(btrim(p_apellido), ''),
    v_email,
    nullif(btrim(p_telefono), ''),
    'admin',
    true,
    null
  );

  return v_empresa_id;
end;
$$;

revoke all on function public.provisionar_empresa_master(uuid, text, text, text, text)
  from public, anon, authenticated;
grant execute on function public.provisionar_empresa_master(uuid, text, text, text, text)
  to service_role;

-- El correo queda ligado a Auth y ningun usuario puede cambiar su propio
-- rol/estado/empresa. La cuenta maestra tampoco puede desactivarse ni
-- transferirse mediante un update ordinario.
create or replace function public.profiles_guard_self_changes()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.id is distinct from old.id
    or new.email is distinct from old.email
    or new.empresa_id is distinct from old.empresa_id
    or new.creado_por is distinct from old.creado_por
    or new.creado_en is distinct from old.creado_en then
    raise exception using message = 'La identidad, empresa y datos de alta del perfil son inmutables.', errcode = '42501';
  end if;
  if new.id = auth.uid() and (
    new.rol is distinct from old.rol
    or new.activo is distinct from old.activo
  ) then
    raise exception using message = 'No puede modificar su propio rol, estado o empresa.', errcode = '42501';
  end if;
  if old.rol = 'admin' and (new.rol is distinct from old.rol or (new.activo is distinct from old.activo and not new.activo))
  then
    raise exception using message = 'La cuenta maestra de la empresa no se puede desactivar ni cambiar de rol.', errcode = '23514';
  end if;
  new.actualizado_en := now();
  return new;
end;
$$;

drop trigger if exists trg_profiles_guard_self_changes on profiles;
create trigger trg_profiles_guard_self_changes
  before update on profiles
  for each row execute function public.profiles_guard_self_changes();

alter table empresas enable row level security;
alter table profiles enable row level security;

drop policy if exists "empresas_select" on empresas;
create policy "empresas_select" on empresas
  for select to authenticated using (id = public.current_empresa_id());

drop policy if exists "profiles_select" on profiles;
drop policy if exists "profiles_insert_admin" on profiles;
drop policy if exists "profiles_update" on profiles;
create policy "profiles_select" on profiles
  for select to authenticated
  using (id = auth.uid() or (empresa_id = public.current_empresa_id() and public.is_admin()));
-- No hay politica INSERT para authenticated. Las fichas se crean unicamente
-- desde las funciones privadas que usan service_role.
create policy "profiles_update" on profiles
  for update to authenticated
  using ((id = auth.uid() and public.is_active_profile()) or (empresa_id = public.current_empresa_id() and public.is_admin()))
  with check ((id = auth.uid() and public.is_active_profile()) or (empresa_id = public.current_empresa_id() and public.is_admin()));

revoke all on table profiles from anon;
revoke insert, delete, truncate, references, trigger on table profiles from authenticated;
grant select, update on table profiles to authenticated;
grant select, insert, update, delete on table profiles to service_role;

-- Cartera: empresa_id aísla entre empresas; prestamista_id reparte la cartera
-- dentro de la empresa (admin ve y gestiona todo; el resto solo lo suyo).
alter table clientes add column if not exists empresa_id uuid;
alter table clientes add column if not exists prestamista_id uuid;
alter table clientes add column if not exists creado_por uuid;
alter table prestamos add column if not exists empresa_id uuid;
alter table prestamos add column if not exists prestamista_id uuid;
alter table prestamos add column if not exists creado_por uuid;
alter table pagos add column if not exists registrado_por uuid;
alter table gestiones add column if not exists creado_por uuid;

do $$
declare
  v_empresa_id uuid;
  v_admin_id uuid;
begin
  select id into v_empresa_id from empresas order by creado_en limit 1;
  select id into v_admin_id from profiles
    where empresa_id = v_empresa_id and rol = 'admin' order by creado_en limit 1;

  update clientes set empresa_id = v_empresa_id where empresa_id is null;
  update clientes set prestamista_id = v_admin_id where prestamista_id is null;
  update clientes set creado_por = v_admin_id where creado_por is null;
  update prestamos set empresa_id = v_empresa_id where empresa_id is null;
  update prestamos set prestamista_id = v_admin_id where prestamista_id is null;
  update prestamos set creado_por = v_admin_id where creado_por is null;
  update pagos set registrado_por = v_admin_id where registrado_por is null;
  update gestiones set creado_por = v_admin_id where creado_por is null;
end $$;

alter table clientes alter column empresa_id set not null;
alter table clientes alter column prestamista_id set not null;
alter table clientes alter column empresa_id set default public.current_empresa_id();
alter table clientes alter column prestamista_id set default auth.uid();
alter table clientes alter column creado_por set default auth.uid();
alter table prestamos alter column empresa_id set not null;
alter table prestamos alter column prestamista_id set not null;
alter table prestamos alter column empresa_id set default public.current_empresa_id();
alter table prestamos alter column prestamista_id set default auth.uid();
alter table prestamos alter column creado_por set default auth.uid();
alter table pagos alter column registrado_por set default auth.uid();
alter table gestiones alter column creado_por set default auth.uid();

-- Claves compuestas: no basta con que el prestamista/cliente exista; debe
-- pertenecer a la misma empresa de la fila que lo referencia.
create unique index if not exists clientes_id_empresa_unique
  on clientes (id, empresa_id);

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'clientes_empresa_fk' and conrelid = 'public.clientes'::regclass) then
    alter table clientes add constraint clientes_empresa_fk foreign key (empresa_id) references empresas(id);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'prestamos_empresa_fk' and conrelid = 'public.prestamos'::regclass) then
    alter table prestamos add constraint prestamos_empresa_fk foreign key (empresa_id) references empresas(id);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'clientes_prestamista_empresa_fk' and conrelid = 'public.clientes'::regclass) then
    alter table clientes add constraint clientes_prestamista_empresa_fk
      foreign key (prestamista_id, empresa_id) references profiles(id, empresa_id);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'clientes_creado_por_empresa_fk' and conrelid = 'public.clientes'::regclass) then
    alter table clientes add constraint clientes_creado_por_empresa_fk
      foreign key (creado_por, empresa_id) references profiles(id, empresa_id);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'prestamos_cliente_empresa_fk' and conrelid = 'public.prestamos'::regclass) then
    alter table prestamos add constraint prestamos_cliente_empresa_fk
      foreign key (cliente_id, empresa_id) references clientes(id, empresa_id);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'prestamos_prestamista_empresa_fk' and conrelid = 'public.prestamos'::regclass) then
    alter table prestamos add constraint prestamos_prestamista_empresa_fk
      foreign key (prestamista_id, empresa_id) references profiles(id, empresa_id);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'prestamos_creado_por_empresa_fk' and conrelid = 'public.prestamos'::regclass) then
    alter table prestamos add constraint prestamos_creado_por_empresa_fk
      foreign key (creado_por, empresa_id) references profiles(id, empresa_id);
  end if;
end $$;

-- Las relaciones simples de versiones anteriores quedan cubiertas por las FK
-- compuestas garantizadas arriba. Mantener ambas hace que PostgREST vea dos
-- caminos entre las mismas tablas y responda HTTP 300 al usar embeds como
-- `prestamos(..., clientes(...))`.
alter table public.prestamos drop constraint if exists prestamos_cliente_id_fkey;
alter table public.clientes drop constraint if exists clientes_prestamista_fk;
alter table public.prestamos drop constraint if exists prestamos_prestamista_fk;

-- `pagos` y `gestiones` derivan la empresa desde el prestamo/cliente. Estos
-- triggers evitan falsificar la autoria con un perfil de otra empresa sin
-- duplicar empresa_id en las tablas historicas.
create or replace function public.validar_autoria_pago()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.registrado_por is not null and not exists (
    select 1
    from public.prestamos prestamo
    join public.profiles autor
      on autor.id = new.registrado_por
      and autor.empresa_id = prestamo.empresa_id
    where prestamo.id = new.prestamo_id
  ) then
    raise exception using
      message = 'Quien registra el pago debe pertenecer a la empresa del prestamo.',
      errcode = '23514';
  end if;
  return new;
end;
$$;

create or replace function public.validar_autoria_gestion()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.creado_por is not null and not exists (
    select 1
    from public.clientes cliente
    join public.profiles autor
      on autor.id = new.creado_por
      and autor.empresa_id = cliente.empresa_id
    where cliente.id = new.cliente_id
  ) then
    raise exception using
      message = 'Quien registra la gestion debe pertenecer a la empresa del cliente.',
      errcode = '23514';
  end if;

  if new.pago_id is not null and not exists (
    select 1
    from public.pagos pago
    join public.prestamos prestamo on prestamo.id = pago.prestamo_id
    where pago.id = new.pago_id and prestamo.cliente_id = new.cliente_id
  ) then
    raise exception using
      message = 'El pago enlazado no pertenece al cliente de la gestion.',
      errcode = '23514';
  end if;
  return new;
end;
$$;

drop trigger if exists trg_pagos_validar_autoria on pagos;
create trigger trg_pagos_validar_autoria
  before insert or update of prestamo_id, registrado_por on pagos
  for each row execute function public.validar_autoria_pago();

drop trigger if exists trg_gestiones_validar_autoria on gestiones;
create trigger trg_gestiones_validar_autoria
  before insert or update of cliente_id, creado_por, pago_id on gestiones
  for each row execute function public.validar_autoria_gestion();

revoke all on function public.validar_autoria_pago() from public, anon, authenticated;
revoke all on function public.validar_autoria_gestion() from public, anon, authenticated;

do $$
begin
  if exists (
    select 1
    from pagos pago
    join prestamos prestamo on prestamo.id = pago.prestamo_id
    join profiles autor on autor.id = pago.registrado_por
    where autor.empresa_id <> prestamo.empresa_id
  ) then
    raise exception 'Existen pagos cuya autoria pertenece a otra empresa';
  end if;

  if exists (
    select 1
    from gestiones gestion
    join clientes cliente on cliente.id = gestion.cliente_id
    join profiles autor on autor.id = gestion.creado_por
    where autor.empresa_id <> cliente.empresa_id
  ) then
    raise exception 'Existen gestiones cuya autoria pertenece a otra empresa';
  end if;

  if exists (
    select 1
    from gestiones gestion
    join pagos pago on pago.id = gestion.pago_id
    join prestamos prestamo on prestamo.id = pago.prestamo_id
    where gestion.pago_id is not null and prestamo.cliente_id <> gestion.cliente_id
  ) then
    raise exception 'Existen gestiones enlazadas a pagos de otro cliente';
  end if;
end $$;

create index if not exists idx_clientes_empresa on clientes (empresa_id);
create index if not exists idx_clientes_prestamista on clientes (prestamista_id);
create index if not exists idx_prestamos_empresa on prestamos (empresa_id);
create index if not exists idx_prestamos_prestamista on prestamos (prestamista_id);

-- RLS: acceso por empresa y por prestamista (los usuarios se crean por
-- invitación desde Configuración → Usuarios, o a mano en el panel de
-- Supabase para el primer administrador).
alter table clientes enable row level security;
alter table prestamos enable row level security;
alter table cuotas enable row level security;
alter table pagos enable row level security;
alter table configuracion_prestamista enable row level security;
alter table pago_aplicaciones enable row level security;
alter table gestiones enable row level security;

drop policy if exists "autenticados" on clientes;
drop policy if exists "clientes_select" on clientes;
drop policy if exists "clientes_insert" on clientes;
drop policy if exists "clientes_update" on clientes;
create policy "clientes_select" on clientes for select to authenticated
  using (empresa_id = public.current_empresa_id() and public.is_active_profile() and (public.is_admin() or prestamista_id = auth.uid()));
create policy "clientes_insert" on clientes for insert to authenticated
  with check (empresa_id = public.current_empresa_id() and public.is_active_profile() and (public.is_admin() or prestamista_id = auth.uid()));
create policy "clientes_update" on clientes for update to authenticated
  using (empresa_id = public.current_empresa_id() and public.is_active_profile() and (public.is_admin() or prestamista_id = auth.uid()))
  with check (empresa_id = public.current_empresa_id() and public.is_active_profile() and (public.is_admin() or prestamista_id = auth.uid()));

drop policy if exists "autenticados" on prestamos;
drop policy if exists "prestamos_select" on prestamos;
drop policy if exists "prestamos_insert" on prestamos;
drop policy if exists "prestamos_update" on prestamos;
create policy "prestamos_select" on prestamos for select to authenticated
  using (empresa_id = public.current_empresa_id() and public.is_active_profile() and (public.is_admin() or prestamista_id = auth.uid()));
create policy "prestamos_insert" on prestamos for insert to authenticated
  with check (empresa_id = public.current_empresa_id() and public.is_active_profile() and (public.is_admin() or prestamista_id = auth.uid()));
create policy "prestamos_update" on prestamos for update to authenticated
  using (empresa_id = public.current_empresa_id() and public.is_active_profile() and (public.is_admin() or prestamista_id = auth.uid()))
  with check (empresa_id = public.current_empresa_id() and public.is_active_profile() and (public.is_admin() or prestamista_id = auth.uid()));

drop policy if exists "autenticados" on cuotas;
drop policy if exists "cuotas_all" on cuotas;
create policy "cuotas_all" on cuotas for all to authenticated
  using (exists (
    select 1 from public.prestamos p
    where p.id = cuotas.prestamo_id and p.empresa_id = public.current_empresa_id()
      and public.is_active_profile() and (public.is_admin() or p.prestamista_id = auth.uid())
  ))
  with check (exists (
    select 1 from public.prestamos p
    where p.id = cuotas.prestamo_id and p.empresa_id = public.current_empresa_id()
      and public.is_active_profile() and (public.is_admin() or p.prestamista_id = auth.uid())
  ));

drop policy if exists "autenticados" on pagos;
drop policy if exists "pagos_all" on pagos;
create policy "pagos_all" on pagos for all to authenticated
  using (exists (
    select 1 from public.prestamos p
    where p.id = pagos.prestamo_id and p.empresa_id = public.current_empresa_id()
      and public.is_active_profile() and (public.is_admin() or p.prestamista_id = auth.uid())
  ))
  with check (exists (
    select 1 from public.prestamos p
    where p.id = pagos.prestamo_id and p.empresa_id = public.current_empresa_id()
      and public.is_active_profile() and (public.is_admin() or p.prestamista_id = auth.uid())
  ));

drop policy if exists "autenticados" on pago_aplicaciones;
drop policy if exists "pago_aplicaciones_all" on pago_aplicaciones;
create policy "pago_aplicaciones_all" on pago_aplicaciones for all to authenticated
  using (exists (
    select 1 from public.prestamos p
    where p.id = pago_aplicaciones.prestamo_id and p.empresa_id = public.current_empresa_id()
      and public.is_active_profile() and (public.is_admin() or p.prestamista_id = auth.uid())
  ))
  with check (exists (
    select 1 from public.prestamos p
    where p.id = pago_aplicaciones.prestamo_id and p.empresa_id = public.current_empresa_id()
      and public.is_active_profile() and (public.is_admin() or p.prestamista_id = auth.uid())
  ));

drop policy if exists "autenticados" on gestiones;
drop policy if exists "gestiones_all" on gestiones;
create policy "gestiones_all" on gestiones for all to authenticated
  using (exists (
    select 1 from public.clientes c
    where c.id = gestiones.cliente_id and c.empresa_id = public.current_empresa_id()
      and public.is_active_profile() and (public.is_admin() or c.prestamista_id = auth.uid())
  ))
  with check (exists (
    select 1 from public.clientes c
    where c.id = gestiones.cliente_id and c.empresa_id = public.current_empresa_id()
      and public.is_active_profile() and (public.is_admin() or c.prestamista_id = auth.uid())
  ));

-- Los datos del negocio (recibos) los lee cualquier usuario activo de la
-- empresa, pero solo un admin puede crearlos o editarlos.
drop policy if exists "autenticados" on configuracion_prestamista;
drop policy if exists "configuracion_leer" on configuracion_prestamista;
drop policy if exists "configuracion_insertar" on configuracion_prestamista;
drop policy if exists "configuracion_actualizar" on configuracion_prestamista;
create policy "configuracion_leer" on configuracion_prestamista
  for select to authenticated
  using (empresa_id = public.current_empresa_id() and public.is_active_profile());
create policy "configuracion_insertar" on configuracion_prestamista
  for insert to authenticated
  with check (id = 1 and empresa_id = public.current_empresa_id() and public.is_admin());
create policy "configuracion_actualizar" on configuracion_prestamista
  for update to authenticated
  using (id = 1 and empresa_id = public.current_empresa_id() and public.is_admin())
  with check (id = 1 and empresa_id = public.current_empresa_id() and public.is_admin());

-- Fotos privadas de fachadas. Se sirven con enlaces temporales y solo los
-- usuarios autenticados pueden leerlas o modificarlas.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'fachadas',
  'fachadas',
  false,
  10485760,
  array['image/jpeg', 'image/png', 'image/webp']::text[]
)
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

-- Acepta el formato nuevo `<empresa>/<cliente>/<archivo>` y, durante la
-- transicion, el legado `<cliente>/<archivo>`. En ambos casos resuelve el
-- cliente real y aplica la misma regla de cartera: master o prestamista
-- asignado. No basta con conocer el UUID de la empresa o del cliente.
create or replace function public.can_access_fachada_path(p_name text)
returns boolean
language sql
security definer
stable
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles perfil
    join public.empresas empresa on empresa.id = perfil.empresa_id and empresa.activo
    join public.clientes cliente
      on cliente.empresa_id = perfil.empresa_id
      and cliente.id::text = case
        when split_part(p_name, '/', 1) = perfil.empresa_id::text
          then split_part(p_name, '/', 2)
        else split_part(p_name, '/', 1)
      end
    where perfil.id = auth.uid()
      and perfil.activo
      and (
        perfil.rol = 'admin'
        or cliente.prestamista_id = perfil.id
      )
      and (
        (
          split_part(p_name, '/', 1) = perfil.empresa_id::text
          and split_part(p_name, '/', 2) = cliente.id::text
          and split_part(p_name, '/', 3) <> ''
        )
        or (
          split_part(p_name, '/', 1) = cliente.id::text
          and split_part(p_name, '/', 2) <> ''
        )
      )
  );
$$;

revoke all on function public.can_access_fachada_path(text) from public, anon;
grant execute on function public.can_access_fachada_path(text) to authenticated;

drop policy if exists "fachadas_leer" on storage.objects;
drop policy if exists "fachadas_insertar" on storage.objects;
drop policy if exists "fachadas_actualizar" on storage.objects;
drop policy if exists "fachadas_eliminar" on storage.objects;
create policy "fachadas_leer" on storage.objects
  for select to authenticated
  using (bucket_id = 'fachadas' and public.can_access_fachada_path(name));
create policy "fachadas_insertar" on storage.objects
  for insert to authenticated
  with check (bucket_id = 'fachadas' and public.can_access_fachada_path(name));
create policy "fachadas_actualizar" on storage.objects
  for update to authenticated
  using (bucket_id = 'fachadas' and public.can_access_fachada_path(name))
  with check (bucket_id = 'fachadas' and public.can_access_fachada_path(name));
create policy "fachadas_eliminar" on storage.objects
  for delete to authenticated
  using (bucket_id = 'fachadas' and public.can_access_fachada_path(name));

revoke all on table configuracion_prestamista from public, anon, authenticated;
grant select, insert, update on table configuracion_prestamista to authenticated;

-- La secuencia de una columna identity puede recibir otro nombre si ya había
-- un objeto homónimo. Resolverla desde el catálogo mantiene la migración segura.
do $$
declare
  v_sequence text;
begin
  v_sequence := pg_get_serial_sequence('public.prestamos', 'numero');
  if v_sequence is null then
    raise exception 'prestamos.numero existe pero no tiene una secuencia identity';
  end if;
  execute format('revoke all on sequence %s from public, anon, authenticated', v_sequence);
  execute format('grant usage, select on sequence %s to authenticated', v_sequence);
end $$;

-- La numeración de recibos también usa identity y se resuelve desde el
-- catálogo para no depender del nombre físico elegido por PostgreSQL.
do $$
declare
  v_sequence text;
begin
  v_sequence := pg_get_serial_sequence('public.pagos', 'numero_recibo');
  if v_sequence is null then
    raise exception 'pagos.numero_recibo existe pero no tiene una secuencia identity';
  end if;
  execute format('revoke all on sequence %s from public, anon, authenticated', v_sequence);
  execute format('grant usage, select on sequence %s to authenticated', v_sequence);
end $$;

-- Crea el préstamo y todas sus cuotas dentro de una sola transacción.
-- Interés fijo total: capital + round(capital * tasa / 100, 2).
-- El calendario coincide con `loanCalculator.ts`: diario cada día calendario,
-- semanal en el próximo día fijo, quincenal cada 15 días y mensual por mes.
-- Los centavos sobrantes se reparten para que la suma coincida con el saldo.
drop function if exists public.crear_prestamo_con_cuotas(uuid, numeric, numeric, integer, text, date);

create or replace function public.crear_prestamo_con_cuotas(
  p_solicitud_id uuid,
  p_cliente_id uuid,
  p_monto numeric,
  p_tasa_interes numeric,
  p_plazo integer,
  p_frecuencia text,
  p_fecha_inicio date,
  p_dia_pago_semana smallint
)
returns uuid
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_prestamo_id uuid;
  v_existing public.prestamos%rowtype;
  v_interes numeric;
  v_total numeric;
  v_total_centavos bigint;
  v_base_centavos bigint;
  v_sobrante bigint;
  v_fecha_primer_pago date;
  v_dia_inicio integer;
  v_delta_dias integer;
begin
  if p_solicitud_id is null then
    raise exception using message = 'La identificación de solicitud es obligatoria', errcode = '23502';
  end if;
  if p_cliente_id is null then
    raise exception using message = 'El cliente es obligatorio', errcode = '23502';
  end if;
  if p_monto is null or p_monto <= 0 or p_monto > 999999999999.99
    or p_monto <> round(p_monto, 2) then
    raise exception using message = 'El capital debe ser positivo y tener máximo dos decimales', errcode = '23514';
  end if;
  if p_tasa_interes is null or p_tasa_interes < 0 or p_tasa_interes > 9999.99
    or p_tasa_interes <> round(p_tasa_interes, 2) then
    raise exception using message = 'La tasa debe estar entre 0 y 9999.99 y tener máximo dos decimales', errcode = '23514';
  end if;
  if p_plazo is null or p_plazo < 1 or p_plazo > 600 then
    raise exception using message = 'El plazo debe estar entre 1 y 600 cuotas', errcode = '23514';
  end if;
  if p_frecuencia is null or p_frecuencia not in ('diario', 'semanal', 'quincenal', 'mensual') then
    raise exception using message = 'La frecuencia no es válida', errcode = '23514';
  end if;
  if p_fecha_inicio is null then
    raise exception using message = 'La fecha de inicio es obligatoria', errcode = '23502';
  end if;
  if p_frecuencia = 'diario' then
    if not (
      (p_plazo = 24 and p_tasa_interes in (15, 20))
      or (p_plazo = 40 and p_tasa_interes in (30, 40))
    ) then
      raise exception using message = 'El plan diario no coincide con un plazo y una tasa permitidos', errcode = '23514';
    end if;
  elsif p_frecuencia = 'semanal' and p_plazo not in (12, 24, 36, 48) then
    raise exception using message = 'El plan semanal solo permite 3, 6, 9 o 12 meses', errcode = '23514';
  elsif p_frecuencia = 'quincenal' and p_plazo not in (18, 24) then
    raise exception using message = 'El plan quincenal solo permite 9 o 12 meses', errcode = '23514';
  end if;

  if p_frecuencia = 'semanal' then
    if p_dia_pago_semana is null or p_dia_pago_semana not between 1 and 6 then
      raise exception using message = 'El día de cobro semanal debe estar entre lunes y sábado', errcode = '23514';
    end if;
  elsif p_dia_pago_semana is not null then
    raise exception using message = 'El día de cobro semanal solo aplica a préstamos semanales', errcode = '23514';
  end if;

  perform 1 from public.clientes where id = p_cliente_id;
  if not found then
    raise exception using message = 'El cliente no existe', errcode = '23503';
  end if;

  v_interes := round(p_monto * p_tasa_interes / 100, 2);
  v_total := p_monto + v_interes;
  if v_total > 999999999999.99 then
    raise exception using message = 'El total del préstamo excede el máximo permitido', errcode = '22003';
  end if;

  v_total_centavos := round(v_total * 100)::bigint;
  v_base_centavos := v_total_centavos / p_plazo;
  v_sobrante := mod(v_total_centavos, p_plazo::bigint);
  if v_base_centavos < 1 then
    raise exception using message = 'El total es demasiado bajo para la cantidad de cuotas', errcode = '23514';
  end if;

  if p_frecuencia = 'semanal' then
    v_dia_inicio := extract(isodow from p_fecha_inicio)::integer;
    v_delta_dias := mod(p_dia_pago_semana::integer - v_dia_inicio + 7, 7);
    if v_delta_dias = 0 then
      v_delta_dias := 7;
    end if;
    v_fecha_primer_pago := p_fecha_inicio + v_delta_dias;
  else
    v_fecha_primer_pago := case p_frecuencia
      when 'diario' then p_fecha_inicio + 1
      when 'quincenal' then p_fecha_inicio + 15
      else (p_fecha_inicio + make_interval(months => 1))::date
    end;
  end if;

  insert into public.prestamos (
    solicitud_id, cliente_id, monto, tasa_interes, plazo, frecuencia,
    fecha_inicio, fecha_primer_pago, dia_pago_semana, tasa_mora, saldo, estado
  ) values (
    p_solicitud_id, p_cliente_id, p_monto, p_tasa_interes, p_plazo, p_frecuencia,
    p_fecha_inicio, v_fecha_primer_pago, p_dia_pago_semana, 1.50, v_total, 'activo'
  )
  on conflict (solicitud_id) do nothing
  returning id into v_prestamo_id;

  if v_prestamo_id is null then
    select * into v_existing
    from public.prestamos
    where solicitud_id = p_solicitud_id;

    if not found then
      raise exception using message = 'No se pudo confirmar la solicitud del préstamo', errcode = '40001';
    end if;
    if v_existing.cliente_id is distinct from p_cliente_id
      or v_existing.monto is distinct from p_monto
      or v_existing.tasa_interes is distinct from p_tasa_interes
      or v_existing.plazo is distinct from p_plazo
      or v_existing.frecuencia is distinct from p_frecuencia
      or v_existing.fecha_inicio is distinct from p_fecha_inicio
      or v_existing.dia_pago_semana is distinct from p_dia_pago_semana then
      raise exception using message = 'La solicitud ya fue usada con datos diferentes', errcode = '23505';
    end if;
    return v_existing.id;
  end if;

  insert into public.cuotas (prestamo_id, numero, fecha_vencimiento, monto, estado)
  select
    v_prestamo_id,
    serie.numero,
    case p_frecuencia
      when 'diario' then p_fecha_inicio + serie.numero
      when 'semanal' then v_fecha_primer_pago + ((serie.numero - 1) * 7)
      when 'quincenal' then p_fecha_inicio + (serie.numero * 15)
      else (p_fecha_inicio + make_interval(months => serie.numero))::date
    end,
    (
      v_base_centavos + case when serie.numero <= v_sobrante then 1 else 0 end
    )::numeric / 100,
    'pendiente'
  from generate_series(1, p_plazo) as serie(numero);

  return v_prestamo_id;
end;
$$;

-- Firma anterior conservada durante el despliegue. Para semanal infiere el
-- día del desembolso; si cae domingo usa lunes porque los cobros son lun-sáb.
create or replace function public.crear_prestamo_con_cuotas(
  p_solicitud_id uuid,
  p_cliente_id uuid,
  p_monto numeric,
  p_tasa_interes numeric,
  p_plazo integer,
  p_frecuencia text,
  p_fecha_inicio date
)
returns uuid
language plpgsql
security invoker
set search_path = ''
as $$
begin
  return public.crear_prestamo_con_cuotas(
    p_solicitud_id,
    p_cliente_id,
    p_monto,
    p_tasa_interes,
    p_plazo,
    p_frecuencia,
    p_fecha_inicio,
    case
      when p_frecuencia = 'semanal' then
        case
          when extract(isodow from p_fecha_inicio)::integer = 7 then 1
          else extract(isodow from p_fecha_inicio)::integer
        end::smallint
      else null::smallint
    end
  );
end;
$$;

revoke all on function public.crear_prestamo_con_cuotas(uuid, uuid, numeric, numeric, integer, text, date, smallint)
  from public, anon;
grant execute on function public.crear_prestamo_con_cuotas(uuid, uuid, numeric, numeric, integer, text, date, smallint)
  to authenticated;
revoke all on function public.crear_prestamo_con_cuotas(uuid, uuid, numeric, numeric, integer, text, date)
  from public, anon;
grant execute on function public.crear_prestamo_con_cuotas(uuid, uuid, numeric, numeric, integer, text, date)
  to authenticated;

-- Registra un solo pago/recibo y reparte su monto entre las cuotas pendientes
-- más antiguas. El bloqueo del préstamo serializa cobros simultáneos.
create or replace function public.registrar_pago(
  p_solicitud_id uuid,
  p_prestamo_id uuid,
  p_monto numeric
)
returns uuid
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_pago public.pagos%rowtype;
  v_prestamo public.prestamos%rowtype;
  v_config public.configuracion_prestamista%rowtype;
  v_cuota record;
  v_total_pendiente numeric;
  v_restante numeric;
  v_aplicar numeric;
  v_saldo_posterior numeric;
  v_estado_posterior text;
  v_prefijo text := 'REC';
  v_digitos integer := 6;
  v_recibo text;
  v_datos_recibo jsonb;
  v_hoy date := (clock_timestamp() at time zone 'America/Tegucigalpa')::date;
begin
  if p_solicitud_id is null then
    raise exception using message = 'La identificación de solicitud es obligatoria', errcode = '23502';
  end if;
  if p_prestamo_id is null then
    raise exception using message = 'El préstamo es obligatorio', errcode = '23502';
  end if;
  if p_monto is null or p_monto <= 0 or p_monto > 999999999999.99
    or p_monto <> round(p_monto, 2) then
    raise exception using message = 'El monto debe ser positivo y tener máximo dos decimales', errcode = '23514';
  end if;

  select * into v_pago
  from public.pagos
  where solicitud_id = p_solicitud_id;
  if found then
    if v_pago.prestamo_id is distinct from p_prestamo_id
      or v_pago.monto is distinct from p_monto then
      raise exception using message = 'La solicitud de pago ya fue usada con datos diferentes', errcode = '23505';
    end if;
    return v_pago.id;
  end if;

  select * into v_prestamo
  from public.prestamos
  where id = p_prestamo_id
  for update;
  if not found then
    raise exception using message = 'El préstamo no existe', errcode = '23503';
  end if;

  -- La solicitud pudo completarse mientras esperaba el bloqueo.
  select * into v_pago
  from public.pagos
  where solicitud_id = p_solicitud_id;
  if found then
    if v_pago.prestamo_id is distinct from p_prestamo_id
      or v_pago.monto is distinct from p_monto then
      raise exception using message = 'La solicitud de pago ya fue usada con datos diferentes', errcode = '23505';
    end if;
    return v_pago.id;
  end if;

  if v_prestamo.estado in ('pagado', 'cancelado') or v_prestamo.saldo <= 0 then
    raise exception using message = 'Este préstamo ya no admite pagos', errcode = '23514';
  end if;
  if p_monto > v_prestamo.saldo then
    raise exception using message = 'El pago no puede superar el saldo actual', errcode = '23514';
  end if;

  perform 1
  from public.cuotas
  where prestamo_id = p_prestamo_id
  order by fecha_vencimiento, numero, id
  for update;

  select coalesce(sum(monto - monto_pagado), 0)
  into v_total_pendiente
  from public.cuotas
  where prestamo_id = p_prestamo_id;
  if v_total_pendiente is distinct from v_prestamo.saldo then
    raise exception using message = 'El saldo del préstamo no coincide con sus cuotas; no se registró el pago', errcode = '23514';
  end if;

  v_saldo_posterior := v_prestamo.saldo - p_monto;
  insert into public.pagos (
    solicitud_id, prestamo_id, cuota_id, fecha, monto, saldo_anterior, saldo_posterior
  ) values (
    p_solicitud_id, p_prestamo_id, null, now(), p_monto, v_prestamo.saldo, v_saldo_posterior
  )
  on conflict (solicitud_id) do nothing
  returning * into v_pago;

  if v_pago.id is null then
    select * into v_pago
    from public.pagos
    where solicitud_id = p_solicitud_id;
    if not found then
      raise exception using message = 'No se pudo confirmar la solicitud de pago', errcode = '40001';
    end if;
    if v_pago.prestamo_id is distinct from p_prestamo_id
      or v_pago.monto is distinct from p_monto then
      raise exception using message = 'La solicitud de pago ya fue usada con datos diferentes', errcode = '23505';
    end if;
    return v_pago.id;
  end if;

  select *
  into v_config
  from public.configuracion_prestamista
  where empresa_id = v_prestamo.empresa_id
  for share;
  v_prefijo := coalesce(nullif(btrim(v_config.prefijo_recibo), ''), 'REC');
  v_digitos := greatest(coalesce(v_config.digitos_recibo, 6), length(v_pago.numero_recibo::text));
  v_recibo := v_prefijo || '-' || lpad(v_pago.numero_recibo::text, v_digitos, '0');
  update public.pagos set recibo = v_recibo where id = v_pago.id;

  v_restante := p_monto;
  for v_cuota in
    select id, numero, fecha_vencimiento, monto, monto_pagado
    from public.cuotas
    where prestamo_id = p_prestamo_id and monto_pagado < monto
    order by fecha_vencimiento, numero, id
  loop
    exit when v_restante = 0;
    v_aplicar := least(v_restante, v_cuota.monto - v_cuota.monto_pagado);

    insert into public.pago_aplicaciones (pago_id, prestamo_id, cuota_id, monto)
    values (v_pago.id, p_prestamo_id, v_cuota.id, v_aplicar);

    update public.cuotas
    set monto_pagado = monto_pagado + v_aplicar,
        estado = case
          when monto_pagado + v_aplicar >= monto then 'pagada'
          when fecha_vencimiento < v_hoy then 'vencida'
          else 'pendiente'
        end
    where id = v_cuota.id;

    v_restante := v_restante - v_aplicar;
  end loop;

  if v_restante <> 0 then
    raise exception using message = 'No fue posible aplicar todo el pago a las cuotas', errcode = '23514';
  end if;

  if v_saldo_posterior = 0 then
    v_estado_posterior := 'pagado';
  elsif exists (
    select 1 from public.cuotas
    where prestamo_id = p_prestamo_id
      and fecha_vencimiento < v_hoy
      and monto_pagado < monto
  ) then
    v_estado_posterior := 'en_mora';
  else
    v_estado_posterior := 'al_dia';
  end if;

  -- Congela los datos visibles del comprobante para que editar después el
  -- cliente o el negocio no cambie recibos históricos.
  select jsonb_build_object(
    'version', 1,
    'numeroRecibo', v_recibo,
    'fecha', v_pago.fecha,
    'clienteNombre', c.nombre,
    'clienteIdentidad', c.identidad,
    'numeroPrestamo', case
      when v_prestamo.numero is not null then 'PRE-' || lpad(v_prestamo.numero::text, greatest(6, length(v_prestamo.numero::text)), '0')
      else 'PRE-' || upper(substr(v_prestamo.id::text, 1, 8))
    end,
    'monto', p_monto,
    'saldoAnterior', v_prestamo.saldo,
    'saldoRestante', v_saldo_posterior,
    'estadoCredito', v_estado_posterior,
    'tasaMora', v_prestamo.tasa_mora,
    'negocio', jsonb_build_object(
      'nombre', coalesce(nullif(btrim(v_config.nombre_negocio), ''), 'MultiPréstamos'),
      'propietario', v_config.nombre_propietario,
      'rtn', v_config.rtn,
      'telefono', v_config.telefono,
      'direccion', v_config.direccion
    ),
    'aplicaciones', coalesce((
      select jsonb_agg(
        jsonb_build_object('numeroCuota', cuota.numero, 'monto', aplicacion.monto)
        order by cuota.numero
      )
      from public.pago_aplicaciones aplicacion
      join public.cuotas cuota on cuota.id = aplicacion.cuota_id
      where aplicacion.pago_id = v_pago.id
    ), '[]'::jsonb)
  )
  into v_datos_recibo
  from public.clientes c
  where c.id = v_prestamo.cliente_id;

  update public.pagos
  set datos_recibo = v_datos_recibo
  where id = v_pago.id;

  update public.cuotas
  set estado = case
    when monto_pagado >= monto then 'pagada'
    when fecha_vencimiento < v_hoy then 'vencida'
    else 'pendiente'
  end
  where prestamo_id = p_prestamo_id;

  update public.prestamos
  set saldo = v_saldo_posterior,
      estado = v_estado_posterior
  where id = p_prestamo_id;

  return v_pago.id;
end;
$$;

revoke all on function public.registrar_pago(uuid, uuid, numeric) from public, anon;
grant execute on function public.registrar_pago(uuid, uuid, numeric) to authenticated;

-- Reasigna un préstamo a otro prestamista de la misma empresa. Solo un admin
-- puede llamarla. El historial (pagos, gestiones) conserva quién los hizo
-- realmente; solo cambia quién administra el préstamo de ahora en adelante.
create or replace function public.reasignar_prestamo(
  p_prestamo_id uuid,
  p_prestamista_id uuid
)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_empresa_id uuid;
  v_updated uuid;
begin
  if not public.is_admin() then
    raise exception using message = 'Solo un administrador puede reasignar préstamos.', errcode = '42501';
  end if;
  v_empresa_id := public.current_empresa_id();

  perform 1 from public.profiles
  where id = p_prestamista_id and empresa_id = v_empresa_id and activo;
  if not found then
    raise exception using message = 'El prestamista indicado no existe o no pertenece a su empresa.', errcode = '23503';
  end if;

  update public.prestamos
  set prestamista_id = p_prestamista_id
  where id = p_prestamo_id and empresa_id = v_empresa_id
  returning id into v_updated;
  if v_updated is null then
    raise exception using message = 'El préstamo no existe.', errcode = '23503';
  end if;
end;
$$;

revoke all on function public.reasignar_prestamo(uuid, uuid) from public, anon;
grant execute on function public.reasignar_prestamo(uuid, uuid) to authenticated;

-- Reasigna un cliente (y por lo tanto su ficha y ruta de cobro) a otro
-- prestamista de la misma empresa, sin tocar los préstamos ya asignados.
create or replace function public.reasignar_cliente(
  p_cliente_id uuid,
  p_prestamista_id uuid
)
returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_empresa_id uuid;
  v_updated uuid;
begin
  if not public.is_admin() then
    raise exception using message = 'Solo un administrador puede reasignar clientes.', errcode = '42501';
  end if;
  v_empresa_id := public.current_empresa_id();

  perform 1 from public.profiles
  where id = p_prestamista_id and empresa_id = v_empresa_id and activo;
  if not found then
    raise exception using message = 'El prestamista indicado no existe o no pertenece a su empresa.', errcode = '23503';
  end if;

  update public.clientes
  set prestamista_id = p_prestamista_id
  where id = p_cliente_id and empresa_id = v_empresa_id
  returning id into v_updated;
  if v_updated is null then
    raise exception using message = 'El cliente no existe.', errcode = '23503';
  end if;
end;
$$;

revoke all on function public.reasignar_cliente(uuid, uuid) from public, anon;
grant execute on function public.reasignar_cliente(uuid, uuid) to authenticated;

-- Refresca vencimientos y mora de calendario al abrir Panel/Cartera. La tasa
-- pactada queda guardada, pero todavía no se suma un recargo monetario al saldo.
create or replace function public.actualizar_estados_cartera()
returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_hoy date := (clock_timestamp() at time zone 'America/Tegucigalpa')::date;
begin
  -- Mantiene el mismo orden de bloqueos que registrar_pago: préstamo → cuotas.
  perform p.id
  from public.prestamos p
  where p.estado <> 'cancelado'
  order by p.id
  for update;

  update public.cuotas
  set estado = case
    when monto_pagado >= monto then 'pagada'
    when fecha_vencimiento < v_hoy then 'vencida'
    else 'pendiente'
  end
  where estado is distinct from case
    when monto_pagado >= monto then 'pagada'
    when fecha_vencimiento < v_hoy then 'vencida'
    else 'pendiente'
  end;

  update public.prestamos p
  set estado = case
    when p.saldo = 0 then 'pagado'
    when exists (
      select 1 from public.cuotas c
      where c.prestamo_id = p.id and c.estado = 'vencida' and c.monto_pagado < c.monto
    ) then 'en_mora'
    when exists (select 1 from public.pagos pg where pg.prestamo_id = p.id) then 'al_dia'
    else 'activo'
  end
  where p.estado <> 'cancelado';
end;
$$;

revoke all on function public.actualizar_estados_cartera() from public, anon;
grant execute on function public.actualizar_estados_cartera() to authenticated;

notify pgrst, 'reload schema';

commit;
