-- MultiPréstamos — esquema inicial.
-- Ejecutar en Supabase: panel → SQL Editor → pegar → Run.
-- El script es repetible: vuelve a crear las políticas RLS con la misma configuración.

begin;

create table if not exists clientes (
  id uuid primary key default gen_random_uuid(),
  nombre text not null,
  identidad text,
  telefono text,
  direccion text,
  lugar_trabajo text,
  referencias text,
  estado text not null default 'activo'
    check (estado in ('activo', 'moroso', 'cancelado')),
  notas text,
  creado_en timestamptz not null default now()
);

-- Un solo prestamista/negocio durante el MVP. No se crea una fila por defecto:
-- su ausencia activa la configuración inicial después del primer login.
create table if not exists configuracion_prestamista (
  id smallint primary key default 1 check (id = 1),
  nombre_negocio text not null check (btrim(nombre_negocio) <> ''),
  nombre_propietario text not null check (btrim(nombre_propietario) <> ''),
  rtn text,
  direccion text,
  telefono text,
  prefijo_recibo text not null default 'REC',
  digitos_recibo smallint not null default 6,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table if not exists prestamos (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity unique,
  cliente_id uuid not null references clientes(id),
  monto numeric(14,2) not null check (monto > 0),
  tasa_interes numeric(6,2) not null default 0
    constraint prestamos_tasa_no_negativa check (tasa_interes >= 0),
  plazo integer not null check (plazo > 0),
  frecuencia text not null check (frecuencia in ('semanal', 'quincenal', 'mensual')),
  fecha_inicio date not null default ((clock_timestamp() at time zone 'America/Tegucigalpa')::date),
  fecha_primer_pago date,
  saldo numeric(14,2) not null
    constraint prestamos_saldo_no_negativo check (saldo >= 0),
  estado text not null default 'activo'
    check (estado in ('activo', 'al_dia', 'en_mora', 'pagado', 'cancelado')),
  solicitud_id uuid,
  creado_en timestamptz not null default now()
);

create table if not exists cuotas (
  id uuid primary key default gen_random_uuid(),
  prestamo_id uuid not null references prestamos(id) on delete cascade,
  numero integer not null
    constraint cuotas_numero_positivo check (numero > 0),
  fecha_vencimiento date not null,
  monto numeric(14,2) not null
    constraint cuotas_monto_positivo check (monto > 0),
  monto_pagado numeric(14,2) not null default 0,
  estado text not null default 'pendiente'
    check (estado in ('pendiente', 'pagada', 'vencida')),
  unique (prestamo_id, numero),
  constraint cuotas_id_prestamo_unique unique (id, prestamo_id)
);

create table if not exists pagos (
  id uuid primary key default gen_random_uuid(),
  prestamo_id uuid not null references prestamos(id),
  cuota_id uuid,
  solicitud_id uuid not null default gen_random_uuid(),
  numero_recibo bigint generated by default as identity unique,
  fecha timestamptz not null default now(),
  monto numeric(14,2) not null check (monto > 0),
  recibo text,
  saldo_anterior numeric(14,2),
  saldo_posterior numeric(14,2),
  notas text,
  datos_recibo jsonb,
  creado_en timestamptz not null default now(),
  constraint pagos_id_prestamo_unique unique (id, prestamo_id),
  constraint pagos_cuota_prestamo_fk
    foreign key (cuota_id, prestamo_id) references cuotas(id, prestamo_id)
);

-- Las FK compuestas necesitan estas claves aun cuando las tablas provengan
-- del esquema anterior. Deben existir antes de crear `pago_aplicaciones`.
do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'cuotas_id_prestamo_unique' and conrelid = 'public.cuotas'::regclass
  ) then
    alter table cuotas add constraint cuotas_id_prestamo_unique unique (id, prestamo_id);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'pagos_id_prestamo_unique' and conrelid = 'public.pagos'::regclass
  ) then
    alter table pagos add constraint pagos_id_prestamo_unique unique (id, prestamo_id);
  end if;
end $$;

-- Un pago puede cubrir varias cuotas. Esta tabla guarda ese reparto mientras
-- `pagos` conserva una sola fila por operación y por recibo.
create table if not exists pago_aplicaciones (
  id uuid primary key default gen_random_uuid(),
  pago_id uuid not null,
  prestamo_id uuid not null,
  cuota_id uuid not null,
  monto numeric(14,2) not null check (monto > 0),
  creado_en timestamptz not null default now(),
  constraint pago_aplicaciones_pago_fk
    foreign key (pago_id, prestamo_id) references pagos(id, prestamo_id) on delete cascade,
  constraint pago_aplicaciones_cuota_fk
    foreign key (cuota_id, prestamo_id) references cuotas(id, prestamo_id),
  constraint pago_aplicaciones_pago_cuota_unique unique (pago_id, cuota_id)
);

-- Migraciones idempotentes para proyectos donde las tablas ya existían antes
-- de agregar estas validaciones.
alter table clientes add column if not exists lugar_trabajo text;
alter table clientes add column if not exists referencias text;
alter table clientes add column if not exists estado text not null default 'activo';

alter table configuracion_prestamista add column if not exists nombre_negocio text;
alter table configuracion_prestamista add column if not exists nombre_propietario text;
alter table configuracion_prestamista add column if not exists rtn text;
alter table configuracion_prestamista add column if not exists direccion text;
alter table configuracion_prestamista add column if not exists telefono text;
alter table configuracion_prestamista add column if not exists prefijo_recibo text not null default 'REC';
alter table configuracion_prestamista add column if not exists digitos_recibo smallint not null default 6;
alter table configuracion_prestamista add column if not exists creado_en timestamptz not null default now();
alter table configuracion_prestamista add column if not exists actualizado_en timestamptz not null default now();

alter table prestamos add column if not exists solicitud_id uuid;
alter table prestamos add column if not exists numero bigint generated by default as identity;
alter table prestamos add column if not exists fecha_primer_pago date;
alter table prestamos alter column fecha_inicio
  set default ((clock_timestamp() at time zone 'America/Tegucigalpa')::date);
alter table cuotas add column if not exists monto_pagado numeric(14,2) not null default 0;
alter table pagos add column if not exists solicitud_id uuid;
alter table pagos add column if not exists numero_recibo bigint generated by default as identity;
alter table pagos add column if not exists saldo_anterior numeric(14,2);
alter table pagos add column if not exists saldo_posterior numeric(14,2);
alter table pagos add column if not exists notas text;
alter table pagos add column if not exists datos_recibo jsonb;
alter table pagos add column if not exists creado_en timestamptz not null default now();

update clientes set estado = 'activo' where estado is null;
alter table clientes alter column estado set default 'activo';
alter table clientes alter column estado set not null;

-- Para préstamos previos toma la cuota 1; si no existe, deriva la fecha con
-- el mismo calendario fijo que utiliza la aplicación.
update prestamos p
set fecha_primer_pago = coalesce(
  (
    select c.fecha_vencimiento
    from cuotas c
    where c.prestamo_id = p.id
      and c.numero = 1
    limit 1
  ),
  case p.frecuencia
    when 'semanal' then p.fecha_inicio + 7
    when 'quincenal' then p.fecha_inicio + 15
    else (p.fecha_inicio + make_interval(months => 1))::date
  end
)
where p.fecha_primer_pago is null;

alter table prestamos alter column numero set not null;
alter table prestamos alter column fecha_primer_pago set not null;

-- Cada pago histórico se conserva como una operación y, cuando apuntaba a
-- una cuota, se migra como una aplicación uno-a-uno sin adivinar agrupaciones.
update pagos set solicitud_id = id where solicitud_id is null;
alter table pagos alter column solicitud_id set not null;
alter table pagos alter column solicitud_id set default gen_random_uuid();

insert into pago_aplicaciones (pago_id, prestamo_id, cuota_id, monto, creado_en)
select id, prestamo_id, cuota_id, monto, fecha
from pagos
where cuota_id is not null
on conflict (pago_id, cuota_id) do nothing;

do $$
begin
  if exists (
    select 1
    from pago_aplicaciones a
    join cuotas c on c.id = a.cuota_id
    group by c.id, c.monto
    having sum(a.monto) > c.monto
  ) then
    raise exception 'Hay pagos históricos que exceden el monto de su cuota';
  end if;
end $$;

update cuotas c
set monto_pagado = datos.total
from (
  select cuota_id, sum(monto) as total
  from pago_aplicaciones
  group by cuota_id
) datos
where c.id = datos.cuota_id;

update cuotas
set monto_pagado = monto
where estado = 'pagada' and monto_pagado = 0;

-- No corregimos diferencias históricas silenciosamente: un saldo que no
-- coincide con sus cuotas debe revisarse antes de aceptar nuevos cobros.
do $$
declare
  v_prestamos text;
begin
  select string_agg(p.id::text, ', ' order by p.id::text)
  into v_prestamos
  from public.prestamos p
  where p.estado <> 'cancelado'
    and p.saldo is distinct from (
    select coalesce(sum(c.monto - c.monto_pagado), 0)
    from public.cuotas c
    where c.prestamo_id = p.id
  );

  if v_prestamos is not null then
    raise exception 'El saldo no coincide con las cuotas en préstamo(s): %', v_prestamos;
  end if;
end $$;

update pagos
set recibo = 'REC-' || lpad(numero_recibo::text, greatest(6, length(numero_recibo::text)), '0')
where recibo is null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'clientes_estado_valido' and conrelid = 'public.clientes'::regclass
  ) then
    alter table clientes add constraint clientes_estado_valido
      check (estado in ('activo', 'moroso', 'cancelado'));
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'configuracion_prestamista_singleton'
      and conrelid = 'public.configuracion_prestamista'::regclass
  ) then
    alter table configuracion_prestamista add constraint configuracion_prestamista_singleton check (id = 1);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'configuracion_nombre_negocio_requerido'
      and conrelid = 'public.configuracion_prestamista'::regclass
  ) then
    alter table configuracion_prestamista add constraint configuracion_nombre_negocio_requerido
      check (nombre_negocio is not null and btrim(nombre_negocio) <> '');
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'configuracion_propietario_requerido'
      and conrelid = 'public.configuracion_prestamista'::regclass
  ) then
    alter table configuracion_prestamista add constraint configuracion_propietario_requerido
      check (nombre_propietario is not null and btrim(nombre_propietario) <> '');
  end if;
  if not exists (select 1 from pg_constraint where conname = 'prestamos_tasa_no_negativa' and conrelid = 'public.prestamos'::regclass) then
    alter table prestamos add constraint prestamos_tasa_no_negativa check (tasa_interes >= 0);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'prestamos_saldo_no_negativo' and conrelid = 'public.prestamos'::regclass) then
    alter table prestamos add constraint prestamos_saldo_no_negativo check (saldo >= 0);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'cuotas_numero_positivo' and conrelid = 'public.cuotas'::regclass) then
    alter table cuotas add constraint cuotas_numero_positivo check (numero > 0);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'cuotas_monto_positivo' and conrelid = 'public.cuotas'::regclass) then
    alter table cuotas add constraint cuotas_monto_positivo check (monto > 0);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'cuotas_monto_pagado_valido' and conrelid = 'public.cuotas'::regclass
  ) then
    alter table cuotas add constraint cuotas_monto_pagado_valido
      check (monto_pagado >= 0 and monto_pagado <= monto);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'cuotas_id_prestamo_unique' and conrelid = 'public.cuotas'::regclass) then
    alter table cuotas add constraint cuotas_id_prestamo_unique unique (id, prestamo_id);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'pagos_cuota_prestamo_fk' and conrelid = 'public.pagos'::regclass) then
    alter table pagos add constraint pagos_cuota_prestamo_fk
      foreign key (cuota_id, prestamo_id) references cuotas(id, prestamo_id);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'pagos_id_prestamo_unique' and conrelid = 'public.pagos'::regclass
  ) then
    alter table pagos add constraint pagos_id_prestamo_unique unique (id, prestamo_id);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'pagos_solicitud_id_unique' and conrelid = 'public.pagos'::regclass
  ) then
    alter table pagos add constraint pagos_solicitud_id_unique unique (solicitud_id);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'configuracion_prefijo_recibo_valido'
      and conrelid = 'public.configuracion_prestamista'::regclass
  ) then
    alter table configuracion_prestamista add constraint configuracion_prefijo_recibo_valido
      check (char_length(btrim(prefijo_recibo)) between 1 and 10);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'configuracion_digitos_recibo_valido'
      and conrelid = 'public.configuracion_prestamista'::regclass
  ) then
    alter table configuracion_prestamista add constraint configuracion_digitos_recibo_valido
      check (digitos_recibo between 3 and 12);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'prestamos_solicitud_id_unique' and conrelid = 'public.prestamos'::regclass) then
    alter table prestamos add constraint prestamos_solicitud_id_unique unique (solicitud_id);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'prestamos_fecha_primer_pago_valida'
      and conrelid = 'public.prestamos'::regclass
  ) then
    alter table prestamos add constraint prestamos_fecha_primer_pago_valida
      check (fecha_primer_pago >= fecha_inicio);
  end if;
end $$;

create index if not exists idx_prestamos_cliente on prestamos (cliente_id);
create unique index if not exists idx_prestamos_numero_unique on prestamos (numero);
create index if not exists idx_prestamos_fecha_primer_pago on prestamos (fecha_primer_pago);
create index if not exists idx_cuotas_prestamo on cuotas (prestamo_id);
create index if not exists idx_pagos_prestamo on pagos (prestamo_id);
create index if not exists idx_pagos_fecha on pagos (fecha);
create unique index if not exists idx_pagos_numero_recibo_unique on pagos (numero_recibo);
create index if not exists idx_pago_aplicaciones_pago on pago_aplicaciones (pago_id);
create index if not exists idx_pago_aplicaciones_cuota on pago_aplicaciones (cuota_id);
create index if not exists idx_pago_aplicaciones_prestamo on pago_aplicaciones (prestamo_id);

-- RLS: acceso total para usuarios autenticados (los usuarios se crean a mano
-- en el panel de Supabase: Authentication → Users → Add user).
-- ponytail: política única de un solo negocio; políticas por rol llegan si algún día hay multi-usuario con permisos.
alter table clientes enable row level security;
alter table prestamos enable row level security;
alter table cuotas enable row level security;
alter table pagos enable row level security;
alter table configuracion_prestamista enable row level security;
alter table pago_aplicaciones enable row level security;

drop policy if exists "autenticados" on clientes;
drop policy if exists "autenticados" on prestamos;
drop policy if exists "autenticados" on cuotas;
drop policy if exists "autenticados" on pagos;
drop policy if exists "autenticados" on configuracion_prestamista;
drop policy if exists "configuracion_leer" on configuracion_prestamista;
drop policy if exists "configuracion_insertar" on configuracion_prestamista;
drop policy if exists "configuracion_actualizar" on configuracion_prestamista;
drop policy if exists "autenticados" on pago_aplicaciones;

create policy "autenticados" on clientes for all to authenticated using (true) with check (true);
create policy "autenticados" on prestamos for all to authenticated using (true) with check (true);
create policy "autenticados" on cuotas for all to authenticated using (true) with check (true);
create policy "autenticados" on pagos for all to authenticated using (true) with check (true);
create policy "configuracion_leer" on configuracion_prestamista
  for select to authenticated using (id = 1);
create policy "configuracion_insertar" on configuracion_prestamista
  for insert to authenticated with check (id = 1);
create policy "configuracion_actualizar" on configuracion_prestamista
  for update to authenticated using (id = 1) with check (id = 1);
create policy "autenticados" on pago_aplicaciones for all to authenticated using (true) with check (true);

revoke all on table configuracion_prestamista from public, anon, authenticated;
grant select, insert, update on table configuracion_prestamista to authenticated;

-- La secuencia de una columna identity puede recibir otro nombre si ya había
-- un objeto homónimo. Resolverla desde el catálogo mantiene la migración segura.
do $$
declare
  v_sequence text;
begin
  v_sequence := pg_get_serial_sequence('public.prestamos', 'numero');
  if v_sequence is null then
    raise exception 'prestamos.numero existe pero no tiene una secuencia identity';
  end if;
  execute format('revoke all on sequence %s from public, anon, authenticated', v_sequence);
  execute format('grant usage, select on sequence %s to authenticated', v_sequence);
end $$;

-- La numeración de recibos también usa identity y se resuelve desde el
-- catálogo para no depender del nombre físico elegido por PostgreSQL.
do $$
declare
  v_sequence text;
begin
  v_sequence := pg_get_serial_sequence('public.pagos', 'numero_recibo');
  if v_sequence is null then
    raise exception 'pagos.numero_recibo existe pero no tiene una secuencia identity';
  end if;
  execute format('revoke all on sequence %s from public, anon, authenticated', v_sequence);
  execute format('grant usage, select on sequence %s to authenticated', v_sequence);
end $$;

-- Crea el préstamo y todas sus cuotas dentro de una sola transacción.
-- Interés fijo total: capital + round(capital * tasa / 100, 2).
-- La primera cuota vence después de un período completo y los centavos
-- sobrantes se reparten para que la suma sea exactamente igual al saldo.
drop function if exists public.crear_prestamo_con_cuotas(uuid, numeric, numeric, integer, text, date);

create or replace function public.crear_prestamo_con_cuotas(
  p_solicitud_id uuid,
  p_cliente_id uuid,
  p_monto numeric,
  p_tasa_interes numeric,
  p_plazo integer,
  p_frecuencia text,
  p_fecha_inicio date
)
returns uuid
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_prestamo_id uuid;
  v_existing public.prestamos%rowtype;
  v_interes numeric;
  v_total numeric;
  v_total_centavos bigint;
  v_base_centavos bigint;
  v_sobrante bigint;
  v_fecha_primer_pago date;
begin
  if p_solicitud_id is null then
    raise exception using message = 'La identificación de solicitud es obligatoria', errcode = '23502';
  end if;
  if p_cliente_id is null then
    raise exception using message = 'El cliente es obligatorio', errcode = '23502';
  end if;
  if p_monto is null or p_monto <= 0 or p_monto > 999999999999.99
    or p_monto <> round(p_monto, 2) then
    raise exception using message = 'El capital debe ser positivo y tener máximo dos decimales', errcode = '23514';
  end if;
  if p_tasa_interes is null or p_tasa_interes < 0 or p_tasa_interes > 9999.99
    or p_tasa_interes <> round(p_tasa_interes, 2) then
    raise exception using message = 'La tasa debe estar entre 0 y 9999.99 y tener máximo dos decimales', errcode = '23514';
  end if;
  if p_plazo is null or p_plazo < 1 or p_plazo > 600 then
    raise exception using message = 'El plazo debe estar entre 1 y 600 cuotas', errcode = '23514';
  end if;
  if p_frecuencia is null or p_frecuencia not in ('semanal', 'quincenal', 'mensual') then
    raise exception using message = 'La frecuencia no es válida', errcode = '23514';
  end if;
  if p_fecha_inicio is null then
    raise exception using message = 'La fecha de inicio es obligatoria', errcode = '23502';
  end if;

  perform 1 from public.clientes where id = p_cliente_id;
  if not found then
    raise exception using message = 'El cliente no existe', errcode = '23503';
  end if;

  v_interes := round(p_monto * p_tasa_interes / 100, 2);
  v_total := p_monto + v_interes;
  if v_total > 999999999999.99 then
    raise exception using message = 'El total del préstamo excede el máximo permitido', errcode = '22003';
  end if;

  v_total_centavos := round(v_total * 100)::bigint;
  v_base_centavos := v_total_centavos / p_plazo;
  v_sobrante := mod(v_total_centavos, p_plazo::bigint);
  if v_base_centavos < 1 then
    raise exception using message = 'El total es demasiado bajo para la cantidad de cuotas', errcode = '23514';
  end if;

  v_fecha_primer_pago := case p_frecuencia
    when 'semanal' then p_fecha_inicio + 7
    when 'quincenal' then p_fecha_inicio + 15
    else (p_fecha_inicio + make_interval(months => 1))::date
  end;

  insert into public.prestamos (
    solicitud_id, cliente_id, monto, tasa_interes, plazo, frecuencia, fecha_inicio, fecha_primer_pago, saldo, estado
  ) values (
    p_solicitud_id, p_cliente_id, p_monto, p_tasa_interes, p_plazo, p_frecuencia, p_fecha_inicio, v_fecha_primer_pago, v_total, 'activo'
  )
  on conflict (solicitud_id) do nothing
  returning id into v_prestamo_id;

  if v_prestamo_id is null then
    select * into v_existing
    from public.prestamos
    where solicitud_id = p_solicitud_id;

    if not found then
      raise exception using message = 'No se pudo confirmar la solicitud del préstamo', errcode = '40001';
    end if;
    if v_existing.cliente_id is distinct from p_cliente_id
      or v_existing.monto is distinct from p_monto
      or v_existing.tasa_interes is distinct from p_tasa_interes
      or v_existing.plazo is distinct from p_plazo
      or v_existing.frecuencia is distinct from p_frecuencia
      or v_existing.fecha_inicio is distinct from p_fecha_inicio then
      raise exception using message = 'La solicitud ya fue usada con datos diferentes', errcode = '23505';
    end if;
    return v_existing.id;
  end if;

  insert into public.cuotas (prestamo_id, numero, fecha_vencimiento, monto, estado)
  select
    v_prestamo_id,
    serie.numero,
    case p_frecuencia
      when 'semanal' then p_fecha_inicio + (serie.numero * 7)
      when 'quincenal' then p_fecha_inicio + (serie.numero * 15)
      else (p_fecha_inicio + make_interval(months => serie.numero))::date
    end,
    (
      v_base_centavos + case when serie.numero <= v_sobrante then 1 else 0 end
    )::numeric / 100,
    'pendiente'
  from generate_series(1, p_plazo) as serie(numero);

  return v_prestamo_id;
end;
$$;

revoke all on function public.crear_prestamo_con_cuotas(uuid, uuid, numeric, numeric, integer, text, date)
  from public, anon;
grant execute on function public.crear_prestamo_con_cuotas(uuid, uuid, numeric, numeric, integer, text, date)
  to authenticated;

-- Registra un solo pago/recibo y reparte su monto entre las cuotas pendientes
-- más antiguas. El bloqueo del préstamo serializa cobros simultáneos.
create or replace function public.registrar_pago(
  p_solicitud_id uuid,
  p_prestamo_id uuid,
  p_monto numeric
)
returns uuid
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_pago public.pagos%rowtype;
  v_prestamo public.prestamos%rowtype;
  v_config public.configuracion_prestamista%rowtype;
  v_cuota record;
  v_total_pendiente numeric;
  v_restante numeric;
  v_aplicar numeric;
  v_saldo_posterior numeric;
  v_estado_posterior text;
  v_prefijo text := 'REC';
  v_digitos integer := 6;
  v_recibo text;
  v_datos_recibo jsonb;
  v_hoy date := (clock_timestamp() at time zone 'America/Tegucigalpa')::date;
begin
  if p_solicitud_id is null then
    raise exception using message = 'La identificación de solicitud es obligatoria', errcode = '23502';
  end if;
  if p_prestamo_id is null then
    raise exception using message = 'El préstamo es obligatorio', errcode = '23502';
  end if;
  if p_monto is null or p_monto <= 0 or p_monto > 999999999999.99
    or p_monto <> round(p_monto, 2) then
    raise exception using message = 'El monto debe ser positivo y tener máximo dos decimales', errcode = '23514';
  end if;

  select * into v_pago
  from public.pagos
  where solicitud_id = p_solicitud_id;
  if found then
    if v_pago.prestamo_id is distinct from p_prestamo_id
      or v_pago.monto is distinct from p_monto then
      raise exception using message = 'La solicitud de pago ya fue usada con datos diferentes', errcode = '23505';
    end if;
    return v_pago.id;
  end if;

  select * into v_prestamo
  from public.prestamos
  where id = p_prestamo_id
  for update;
  if not found then
    raise exception using message = 'El préstamo no existe', errcode = '23503';
  end if;

  -- La solicitud pudo completarse mientras esperaba el bloqueo.
  select * into v_pago
  from public.pagos
  where solicitud_id = p_solicitud_id;
  if found then
    if v_pago.prestamo_id is distinct from p_prestamo_id
      or v_pago.monto is distinct from p_monto then
      raise exception using message = 'La solicitud de pago ya fue usada con datos diferentes', errcode = '23505';
    end if;
    return v_pago.id;
  end if;

  if v_prestamo.estado in ('pagado', 'cancelado') or v_prestamo.saldo <= 0 then
    raise exception using message = 'Este préstamo ya no admite pagos', errcode = '23514';
  end if;
  if p_monto > v_prestamo.saldo then
    raise exception using message = 'El pago no puede superar el saldo actual', errcode = '23514';
  end if;

  perform 1
  from public.cuotas
  where prestamo_id = p_prestamo_id
  order by fecha_vencimiento, numero, id
  for update;

  select coalesce(sum(monto - monto_pagado), 0)
  into v_total_pendiente
  from public.cuotas
  where prestamo_id = p_prestamo_id;
  if v_total_pendiente is distinct from v_prestamo.saldo then
    raise exception using message = 'El saldo del préstamo no coincide con sus cuotas; no se registró el pago', errcode = '23514';
  end if;

  v_saldo_posterior := v_prestamo.saldo - p_monto;
  insert into public.pagos (
    solicitud_id, prestamo_id, cuota_id, fecha, monto, saldo_anterior, saldo_posterior
  ) values (
    p_solicitud_id, p_prestamo_id, null, now(), p_monto, v_prestamo.saldo, v_saldo_posterior
  )
  on conflict (solicitud_id) do nothing
  returning * into v_pago;

  if v_pago.id is null then
    select * into v_pago
    from public.pagos
    where solicitud_id = p_solicitud_id;
    if not found then
      raise exception using message = 'No se pudo confirmar la solicitud de pago', errcode = '40001';
    end if;
    if v_pago.prestamo_id is distinct from p_prestamo_id
      or v_pago.monto is distinct from p_monto then
      raise exception using message = 'La solicitud de pago ya fue usada con datos diferentes', errcode = '23505';
    end if;
    return v_pago.id;
  end if;

  select *
  into v_config
  from public.configuracion_prestamista
  where id = 1
  for share;
  v_prefijo := coalesce(nullif(btrim(v_config.prefijo_recibo), ''), 'REC');
  v_digitos := greatest(coalesce(v_config.digitos_recibo, 6), length(v_pago.numero_recibo::text));
  v_recibo := v_prefijo || '-' || lpad(v_pago.numero_recibo::text, v_digitos, '0');
  update public.pagos set recibo = v_recibo where id = v_pago.id;

  v_restante := p_monto;
  for v_cuota in
    select id, numero, fecha_vencimiento, monto, monto_pagado
    from public.cuotas
    where prestamo_id = p_prestamo_id and monto_pagado < monto
    order by fecha_vencimiento, numero, id
  loop
    exit when v_restante = 0;
    v_aplicar := least(v_restante, v_cuota.monto - v_cuota.monto_pagado);

    insert into public.pago_aplicaciones (pago_id, prestamo_id, cuota_id, monto)
    values (v_pago.id, p_prestamo_id, v_cuota.id, v_aplicar);

    update public.cuotas
    set monto_pagado = monto_pagado + v_aplicar,
        estado = case
          when monto_pagado + v_aplicar >= monto then 'pagada'
          when fecha_vencimiento < v_hoy then 'vencida'
          else 'pendiente'
        end
    where id = v_cuota.id;

    v_restante := v_restante - v_aplicar;
  end loop;

  if v_restante <> 0 then
    raise exception using message = 'No fue posible aplicar todo el pago a las cuotas', errcode = '23514';
  end if;

  -- Congela los datos visibles del comprobante para que editar después el
  -- cliente o el negocio no cambie recibos históricos.
  select jsonb_build_object(
    'version', 1,
    'numeroRecibo', v_recibo,
    'fecha', v_pago.fecha,
    'clienteNombre', c.nombre,
    'clienteIdentidad', c.identidad,
    'numeroPrestamo', case
      when v_prestamo.numero is not null then 'PRE-' || lpad(v_prestamo.numero::text, greatest(6, length(v_prestamo.numero::text)), '0')
      else 'PRE-' || upper(substr(v_prestamo.id::text, 1, 8))
    end,
    'monto', p_monto,
    'saldoAnterior', v_prestamo.saldo,
    'saldoRestante', v_saldo_posterior,
    'negocio', jsonb_build_object(
      'nombre', coalesce(nullif(btrim(v_config.nombre_negocio), ''), 'MultiPréstamos'),
      'propietario', v_config.nombre_propietario,
      'rtn', v_config.rtn,
      'telefono', v_config.telefono,
      'direccion', v_config.direccion
    ),
    'aplicaciones', coalesce((
      select jsonb_agg(
        jsonb_build_object('numeroCuota', cuota.numero, 'monto', aplicacion.monto)
        order by cuota.numero
      )
      from public.pago_aplicaciones aplicacion
      join public.cuotas cuota on cuota.id = aplicacion.cuota_id
      where aplicacion.pago_id = v_pago.id
    ), '[]'::jsonb)
  )
  into v_datos_recibo
  from public.clientes c
  where c.id = v_prestamo.cliente_id;

  update public.pagos
  set datos_recibo = v_datos_recibo
  where id = v_pago.id;

  update public.cuotas
  set estado = case
    when monto_pagado >= monto then 'pagada'
    when fecha_vencimiento < v_hoy then 'vencida'
    else 'pendiente'
  end
  where prestamo_id = p_prestamo_id;

  if v_saldo_posterior = 0 then
    v_estado_posterior := 'pagado';
  elsif exists (
    select 1 from public.cuotas
    where prestamo_id = p_prestamo_id and estado = 'vencida' and monto_pagado < monto
  ) then
    v_estado_posterior := 'en_mora';
  else
    v_estado_posterior := 'al_dia';
  end if;

  update public.prestamos
  set saldo = v_saldo_posterior,
      estado = v_estado_posterior
  where id = p_prestamo_id;

  return v_pago.id;
end;
$$;

revoke all on function public.registrar_pago(uuid, uuid, numeric) from public, anon;
grant execute on function public.registrar_pago(uuid, uuid, numeric) to authenticated;

-- Refresca vencimientos y mora de calendario al abrir Panel/Cartera. No
-- calcula recargo monetario: la mora diaria permanece desactivada en el MVP.
create or replace function public.actualizar_estados_cartera()
returns void
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_hoy date := (clock_timestamp() at time zone 'America/Tegucigalpa')::date;
begin
  -- Mantiene el mismo orden de bloqueos que registrar_pago: préstamo → cuotas.
  perform p.id
  from public.prestamos p
  where p.estado <> 'cancelado'
  order by p.id
  for update;

  update public.cuotas
  set estado = case
    when monto_pagado >= monto then 'pagada'
    when fecha_vencimiento < v_hoy then 'vencida'
    else 'pendiente'
  end
  where estado is distinct from case
    when monto_pagado >= monto then 'pagada'
    when fecha_vencimiento < v_hoy then 'vencida'
    else 'pendiente'
  end;

  update public.prestamos p
  set estado = case
    when p.saldo = 0 then 'pagado'
    when exists (
      select 1 from public.cuotas c
      where c.prestamo_id = p.id and c.estado = 'vencida' and c.monto_pagado < c.monto
    ) then 'en_mora'
    when exists (select 1 from public.pagos pg where pg.prestamo_id = p.id) then 'al_dia'
    else 'activo'
  end
  where p.estado <> 'cancelado';
end;
$$;

revoke all on function public.actualizar_estados_cartera() from public, anon;
grant execute on function public.actualizar_estados_cartera() to authenticated;

notify pgrst, 'reload schema';

commit;
