-- MultiPréstamos — esquema inicial.
-- Ejecutar en Supabase: panel → SQL Editor → pegar → Run.
-- El script es repetible: vuelve a crear las políticas RLS con la misma configuración.

create table if not exists clientes (
  id uuid primary key default gen_random_uuid(),
  nombre text not null,
  identidad text,
  telefono text,
  direccion text,
  lugar_trabajo text,
  referencias text,
  estado text not null default 'activo'
    check (estado in ('activo', 'moroso', 'cancelado')),
  notas text,
  creado_en timestamptz not null default now()
);

-- Un solo prestamista/negocio durante el MVP. No se crea una fila por defecto:
-- su ausencia activa la configuración inicial después del primer login.
create table if not exists configuracion_prestamista (
  id smallint primary key default 1 check (id = 1),
  nombre_negocio text not null check (btrim(nombre_negocio) <> ''),
  nombre_propietario text not null check (btrim(nombre_propietario) <> ''),
  rtn text,
  direccion text,
  telefono text,
  creado_en timestamptz not null default now(),
  actualizado_en timestamptz not null default now()
);

create table if not exists prestamos (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity unique,
  cliente_id uuid not null references clientes(id),
  monto numeric(14,2) not null check (monto > 0),
  tasa_interes numeric(6,2) not null default 0
    constraint prestamos_tasa_no_negativa check (tasa_interes >= 0),
  plazo integer not null check (plazo > 0),
  frecuencia text not null check (frecuencia in ('semanal', 'quincenal', 'mensual')),
  fecha_inicio date not null default current_date,
  fecha_primer_pago date,
  saldo numeric(14,2) not null
    constraint prestamos_saldo_no_negativo check (saldo >= 0),
  estado text not null default 'activo'
    check (estado in ('activo', 'al_dia', 'en_mora', 'pagado', 'cancelado')),
  solicitud_id uuid,
  creado_en timestamptz not null default now()
);

create table if not exists cuotas (
  id uuid primary key default gen_random_uuid(),
  prestamo_id uuid not null references prestamos(id) on delete cascade,
  numero integer not null
    constraint cuotas_numero_positivo check (numero > 0),
  fecha_vencimiento date not null,
  monto numeric(14,2) not null
    constraint cuotas_monto_positivo check (monto > 0),
  estado text not null default 'pendiente'
    check (estado in ('pendiente', 'pagada', 'vencida')),
  unique (prestamo_id, numero),
  constraint cuotas_id_prestamo_unique unique (id, prestamo_id)
);

create table if not exists pagos (
  id uuid primary key default gen_random_uuid(),
  prestamo_id uuid not null references prestamos(id),
  cuota_id uuid,
  fecha timestamptz not null default now(),
  monto numeric(14,2) not null check (monto > 0),
  recibo text,
  constraint pagos_cuota_prestamo_fk
    foreign key (cuota_id, prestamo_id) references cuotas(id, prestamo_id)
);

-- Migraciones idempotentes para proyectos donde las tablas ya existían antes
-- de agregar estas validaciones.
alter table clientes add column if not exists lugar_trabajo text;
alter table clientes add column if not exists referencias text;
alter table clientes add column if not exists estado text not null default 'activo';

alter table configuracion_prestamista add column if not exists nombre_negocio text;
alter table configuracion_prestamista add column if not exists nombre_propietario text;
alter table configuracion_prestamista add column if not exists rtn text;
alter table configuracion_prestamista add column if not exists direccion text;
alter table configuracion_prestamista add column if not exists telefono text;
alter table configuracion_prestamista add column if not exists creado_en timestamptz not null default now();
alter table configuracion_prestamista add column if not exists actualizado_en timestamptz not null default now();

alter table prestamos add column if not exists solicitud_id uuid;
alter table prestamos add column if not exists numero bigint generated by default as identity;
alter table prestamos add column if not exists fecha_primer_pago date;

update clientes set estado = 'activo' where estado is null;
alter table clientes alter column estado set default 'activo';
alter table clientes alter column estado set not null;

-- Para préstamos previos toma la cuota 1; si no existe, deriva la fecha con
-- el mismo calendario fijo que utiliza la aplicación.
update prestamos p
set fecha_primer_pago = coalesce(
  (
    select c.fecha_vencimiento
    from cuotas c
    where c.prestamo_id = p.id
      and c.numero = 1
    limit 1
  ),
  case p.frecuencia
    when 'semanal' then p.fecha_inicio + 7
    when 'quincenal' then p.fecha_inicio + 15
    else (p.fecha_inicio + make_interval(months => 1))::date
  end
)
where p.fecha_primer_pago is null;

alter table prestamos alter column numero set not null;
alter table prestamos alter column fecha_primer_pago set not null;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'clientes_estado_valido' and conrelid = 'public.clientes'::regclass
  ) then
    alter table clientes add constraint clientes_estado_valido
      check (estado in ('activo', 'moroso', 'cancelado'));
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'configuracion_prestamista_singleton'
      and conrelid = 'public.configuracion_prestamista'::regclass
  ) then
    alter table configuracion_prestamista add constraint configuracion_prestamista_singleton check (id = 1);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'configuracion_nombre_negocio_requerido'
      and conrelid = 'public.configuracion_prestamista'::regclass
  ) then
    alter table configuracion_prestamista add constraint configuracion_nombre_negocio_requerido
      check (nombre_negocio is not null and btrim(nombre_negocio) <> '');
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'configuracion_propietario_requerido'
      and conrelid = 'public.configuracion_prestamista'::regclass
  ) then
    alter table configuracion_prestamista add constraint configuracion_propietario_requerido
      check (nombre_propietario is not null and btrim(nombre_propietario) <> '');
  end if;
  if not exists (select 1 from pg_constraint where conname = 'prestamos_tasa_no_negativa') then
    alter table prestamos add constraint prestamos_tasa_no_negativa check (tasa_interes >= 0);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'prestamos_saldo_no_negativo') then
    alter table prestamos add constraint prestamos_saldo_no_negativo check (saldo >= 0);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'cuotas_numero_positivo') then
    alter table cuotas add constraint cuotas_numero_positivo check (numero > 0);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'cuotas_monto_positivo') then
    alter table cuotas add constraint cuotas_monto_positivo check (monto > 0);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'cuotas_id_prestamo_unique') then
    alter table cuotas add constraint cuotas_id_prestamo_unique unique (id, prestamo_id);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'pagos_cuota_prestamo_fk') then
    alter table pagos add constraint pagos_cuota_prestamo_fk
      foreign key (cuota_id, prestamo_id) references cuotas(id, prestamo_id);
  end if;
  if not exists (select 1 from pg_constraint where conname = 'prestamos_solicitud_id_unique') then
    alter table prestamos add constraint prestamos_solicitud_id_unique unique (solicitud_id);
  end if;
  if not exists (
    select 1 from pg_constraint
    where conname = 'prestamos_fecha_primer_pago_valida'
      and conrelid = 'public.prestamos'::regclass
  ) then
    alter table prestamos add constraint prestamos_fecha_primer_pago_valida
      check (fecha_primer_pago >= fecha_inicio);
  end if;
end $$;

create index if not exists idx_prestamos_cliente on prestamos (cliente_id);
create unique index if not exists idx_prestamos_numero_unique on prestamos (numero);
create index if not exists idx_prestamos_fecha_primer_pago on prestamos (fecha_primer_pago);
create index if not exists idx_cuotas_prestamo on cuotas (prestamo_id);
create index if not exists idx_pagos_prestamo on pagos (prestamo_id);
create index if not exists idx_pagos_fecha on pagos (fecha);

-- RLS: acceso total para usuarios autenticados (los usuarios se crean a mano
-- en el panel de Supabase: Authentication → Users → Add user).
-- ponytail: política única de un solo negocio; políticas por rol llegan si algún día hay multi-usuario con permisos.
alter table clientes enable row level security;
alter table prestamos enable row level security;
alter table cuotas enable row level security;
alter table pagos enable row level security;
alter table configuracion_prestamista enable row level security;

drop policy if exists "autenticados" on clientes;
drop policy if exists "autenticados" on prestamos;
drop policy if exists "autenticados" on cuotas;
drop policy if exists "autenticados" on pagos;
drop policy if exists "autenticados" on configuracion_prestamista;
drop policy if exists "configuracion_leer" on configuracion_prestamista;
drop policy if exists "configuracion_insertar" on configuracion_prestamista;
drop policy if exists "configuracion_actualizar" on configuracion_prestamista;

create policy "autenticados" on clientes for all to authenticated using (true) with check (true);
create policy "autenticados" on prestamos for all to authenticated using (true) with check (true);
create policy "autenticados" on cuotas for all to authenticated using (true) with check (true);
create policy "autenticados" on pagos for all to authenticated using (true) with check (true);
create policy "configuracion_leer" on configuracion_prestamista
  for select to authenticated using (id = 1);
create policy "configuracion_insertar" on configuracion_prestamista
  for insert to authenticated with check (id = 1);
create policy "configuracion_actualizar" on configuracion_prestamista
  for update to authenticated using (id = 1) with check (id = 1);

revoke all on table configuracion_prestamista from public, anon, authenticated;
grant select, insert, update on table configuracion_prestamista to authenticated;

-- La secuencia de una columna identity puede recibir otro nombre si ya había
-- un objeto homónimo. Resolverla desde el catálogo mantiene la migración segura.
do $$
declare
  v_sequence text;
begin
  v_sequence := pg_get_serial_sequence('public.prestamos', 'numero');
  if v_sequence is null then
    raise exception 'prestamos.numero existe pero no tiene una secuencia identity';
  end if;
  execute format('revoke all on sequence %s from public, anon, authenticated', v_sequence);
  execute format('grant usage, select on sequence %s to authenticated', v_sequence);
end $$;

-- Crea el préstamo y todas sus cuotas dentro de una sola transacción.
-- Interés fijo total: capital + round(capital * tasa / 100, 2).
-- La primera cuota vence después de un período completo y los centavos
-- sobrantes se reparten para que la suma sea exactamente igual al saldo.
drop function if exists public.crear_prestamo_con_cuotas(uuid, numeric, numeric, integer, text, date);

create or replace function public.crear_prestamo_con_cuotas(
  p_solicitud_id uuid,
  p_cliente_id uuid,
  p_monto numeric,
  p_tasa_interes numeric,
  p_plazo integer,
  p_frecuencia text,
  p_fecha_inicio date
)
returns uuid
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_prestamo_id uuid;
  v_existing public.prestamos%rowtype;
  v_interes numeric;
  v_total numeric;
  v_total_centavos bigint;
  v_base_centavos bigint;
  v_sobrante bigint;
  v_fecha_primer_pago date;
begin
  if p_solicitud_id is null then
    raise exception using message = 'La identificación de solicitud es obligatoria', errcode = '23502';
  end if;
  if p_cliente_id is null then
    raise exception using message = 'El cliente es obligatorio', errcode = '23502';
  end if;
  if p_monto is null or p_monto <= 0 or p_monto > 999999999999.99
    or p_monto <> round(p_monto, 2) then
    raise exception using message = 'El capital debe ser positivo y tener máximo dos decimales', errcode = '23514';
  end if;
  if p_tasa_interes is null or p_tasa_interes < 0 or p_tasa_interes > 9999.99
    or p_tasa_interes <> round(p_tasa_interes, 2) then
    raise exception using message = 'La tasa debe estar entre 0 y 9999.99 y tener máximo dos decimales', errcode = '23514';
  end if;
  if p_plazo is null or p_plazo < 1 or p_plazo > 600 then
    raise exception using message = 'El plazo debe estar entre 1 y 600 cuotas', errcode = '23514';
  end if;
  if p_frecuencia is null or p_frecuencia not in ('semanal', 'quincenal', 'mensual') then
    raise exception using message = 'La frecuencia no es válida', errcode = '23514';
  end if;
  if p_fecha_inicio is null then
    raise exception using message = 'La fecha de inicio es obligatoria', errcode = '23502';
  end if;

  perform 1 from public.clientes where id = p_cliente_id;
  if not found then
    raise exception using message = 'El cliente no existe', errcode = '23503';
  end if;

  v_interes := round(p_monto * p_tasa_interes / 100, 2);
  v_total := p_monto + v_interes;
  if v_total > 999999999999.99 then
    raise exception using message = 'El total del préstamo excede el máximo permitido', errcode = '22003';
  end if;

  v_total_centavos := round(v_total * 100)::bigint;
  v_base_centavos := v_total_centavos / p_plazo;
  v_sobrante := mod(v_total_centavos, p_plazo::bigint);
  if v_base_centavos < 1 then
    raise exception using message = 'El total es demasiado bajo para la cantidad de cuotas', errcode = '23514';
  end if;

  v_fecha_primer_pago := case p_frecuencia
    when 'semanal' then p_fecha_inicio + 7
    when 'quincenal' then p_fecha_inicio + 15
    else (p_fecha_inicio + make_interval(months => 1))::date
  end;

  insert into public.prestamos (
    solicitud_id, cliente_id, monto, tasa_interes, plazo, frecuencia, fecha_inicio, fecha_primer_pago, saldo, estado
  ) values (
    p_solicitud_id, p_cliente_id, p_monto, p_tasa_interes, p_plazo, p_frecuencia, p_fecha_inicio, v_fecha_primer_pago, v_total, 'activo'
  )
  on conflict (solicitud_id) do nothing
  returning id into v_prestamo_id;

  if v_prestamo_id is null then
    select * into v_existing
    from public.prestamos
    where solicitud_id = p_solicitud_id;

    if not found then
      raise exception using message = 'No se pudo confirmar la solicitud del préstamo', errcode = '40001';
    end if;
    if v_existing.cliente_id is distinct from p_cliente_id
      or v_existing.monto is distinct from p_monto
      or v_existing.tasa_interes is distinct from p_tasa_interes
      or v_existing.plazo is distinct from p_plazo
      or v_existing.frecuencia is distinct from p_frecuencia
      or v_existing.fecha_inicio is distinct from p_fecha_inicio then
      raise exception using message = 'La solicitud ya fue usada con datos diferentes', errcode = '23505';
    end if;
    return v_existing.id;
  end if;

  insert into public.cuotas (prestamo_id, numero, fecha_vencimiento, monto, estado)
  select
    v_prestamo_id,
    serie.numero,
    case p_frecuencia
      when 'semanal' then p_fecha_inicio + (serie.numero * 7)
      when 'quincenal' then p_fecha_inicio + (serie.numero * 15)
      else (p_fecha_inicio + make_interval(months => serie.numero))::date
    end,
    (
      v_base_centavos + case when serie.numero <= v_sobrante then 1 else 0 end
    )::numeric / 100,
    'pendiente'
  from generate_series(1, p_plazo) as serie(numero);

  return v_prestamo_id;
end;
$$;

revoke all on function public.crear_prestamo_con_cuotas(uuid, uuid, numeric, numeric, integer, text, date)
  from public, anon;
grant execute on function public.crear_prestamo_con_cuotas(uuid, uuid, numeric, numeric, integer, text, date)
  to authenticated;

notify pgrst, 'reload schema';
